In [2]:
# Import necessary libraries.
from sklearn.linear_model import LogisticRegression # Logistic Regression model
from sklearn.ensemble import RandomForestClassifier # Random Forest classifier
from sklearn.model_selection import train_test_split, GridSearchCV # Modules for splitting train/test data and for Grid Search
from sklearn.feature_selection import SelectKBest, VarianceThreshold, f_classif # Modules for feature selection (Select top K, Variance Threshold, ANOVA F-value)
from sklearn.tree import DecisionTreeClassifier # Decision Tree classifier
from sklearn.metrics import roc_auc_score, fbeta_score, make_scorer # ROC AUC score, F-beta score, create custom scorer
from xgboost import XGBClassifier # XGBoost classifier
import shap # SHAP(SHapley Additive exPlanations) library (explaining model predictions)
import matplotlib.pyplot as plt # Library for data visualization

import pandas as pd # Library for data manipulation and analysis
import numpy as np # Library for numerical calculations
import datetime as dt # Library for date and time handling
import json # Library for JSON data handling

In [3]:
# Module for handling warning messages
import warnings 

# Ignore only the 'use_label_encoder' warning.
warnings.filterwarnings("ignore")

#### prepare "data/initial_dataset.p"

In [4]:
# # .xlsx -> .p : 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP_JPP with 3Lots_FT1_FT2_FT3

# # Specify the file path
# file_path = 'data/1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP_JPP with 3Lots_FT1_FT2_FT3.xlsx'

# # Read the Excel file into a DataFrame
# # By default, it reads the first sheet.
# data_row = pd.read_excel(file_path)

# # Define the file path
# output_file_path = 'data/1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP_JPP with 3Lots_FT1_FT2_FT3.p'

# # Save the DataFrame to a pickle file
# data_row.to_pickle(output_file_path)

In [5]:
# # .xlsx -> .p : 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP_JPP with QualWfrs_FT&QAwithQAAfterStress

# # Specify the file path
# file_path = 'data\\1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP_JPP with QualWfrs_FT&QAwithQAAfterStress.xlsx'

# # Read the Excel file into a DataFrame
# # By default, it reads the first sheet.
# data_row = pd.read_excel(file_path)

# # Define the file path
# output_file_path = 'data\\1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP_JPP with QualWfrs_FT&QAwithQAAfterStress.p'

# # Save the DataFrame to a pickle file
# data_row.to_pickle(output_file_path)

In [6]:
# read *.p
pickle_file_path_1 = 'data\\1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP_JPP with 3Lots_FT1_FT2_FT3.p'
data_row_1 = pd.read_pickle(pickle_file_path_1)
pickle_file_path_2 = 'data\\1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP_JPP with QualWfrs_FT&QAwithQAAfterStress.p'
data_row_2 = pd.read_pickle(pickle_file_path_2)

In [7]:
# Keep only the necessary columns

# Specify the file path
file_path = 'data/cols_to_keep.csv'

# Read the CSV file into a DataFrame
cols_to_keep_df = pd.read_csv(file_path)

cols_to_keep = cols_to_keep_df.iloc[:, 0].tolist()

data_row_1 = data_row_1[cols_to_keep]

In [8]:
# data_row <= data_row1 data_row2

# Select only the columns to join from data_row_2
columns_to_join = ['DevID of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP_JPP',
                   'BG pass/fail']

# Create a subset DataFrame of data_row_2 with the selected columns
data_row_2_subset = data_row_2[columns_to_join]

# Merge the selected columns from data_row_2 into data_row_1 using the 'DevID' join key
data_row = pd.merge(data_row_1, data_row_2_subset, on='DevID of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP_JPP', how='left')

In [9]:
initial_dataset = data_row.copy() # Copy the original dataset

In [10]:
# prepare for target

initial_dataset['Pass/Fail_pass'] = ((initial_dataset['soft_bin of FT1'] == 1) &
                   (initial_dataset['soft_bin of FT2'] == 1) &
                   (initial_dataset['soft_bin'] == 1)).astype(int)

In [11]:
# prepare for base model

initial_dataset['band gap dpat'] = initial_dataset['BG pass/fail'].apply(lambda x: 'bandGapFail' if x == 'impossible wafer' else 'ok for band gap')

# Create a dictionary for column name changes
new_column_names = {
    'wafer_id': 'WAFER_NO',
    'DevID of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP_JPP': 'DevID'
}

# Rename the columns using the .rename() method (using inplace=True to apply directly to the original DataFrame)
initial_dataset.rename(columns=new_column_names, inplace=True)

In [12]:
initial_dataset

,WF of 1103959_69_1133529_cp1,ROW of 1103959_69_1133529_cp1,COL of 1103959_69_1133529_cp1,DevID,S of 1103959_69_1133529_cp1,F:E of 1103959_69_1133529_cp1,FAILING_BINOUTS(1) of 1103959_69_1133529_cp1,HH_CONT_OUT of 1103959_69_1133529_cp1,HH_CONT_CL of 1103959_69_1133529_cp1,HH_CONT_CM of 1103959_69_1133529_cp1,...,EEPROM_T_SCAL_G_BIAS[],EEPROM_V4[],EEPROM_BANK8_D[],EEPROM_BANK8_C[],EEPROM_BANK9_D[],EEPROM_BANK9_C[],EEPROM_LOCKPAT_check[],BG pass/fail,Pass/Fail_pass,band gap dpat
0,2,17,35,[110395 17 35],8,.:.,NaN,-0.3747,-0.3812,-0.3783,...,4.0,122.0,35.0,199.0,18.0,123.0,83.0,impossible wafer,1,bandGapFail
1,2,19,38,[110395 19 38],8,.:.,NaN,-0.3849,-0.3934,-0.3894,...,3.0,140.0,35.0,199.0,18.0,123.0,83.0,NaN,1,ok for band gap
2,2,-7,63,[110395 -7 63],8,.:.,NaN,-0.3859,-0.3815,-0.3792,...,243.0,128.0,35.0,199.0,18.0,123.0,83.0,impossible wafer,1,bandGapFail
3,2,13,70,[110395 13 70],8,.:.,NaN,-0.3928,-0.3833,-0.3811,...,4.0,96.0,36.0,71.0,18.0,123.0,83.0,NaN,1,ok for band gap
4,2,33,57,[110395 33 57],8,.:.,NaN,-0.3875,-0.3796,-0.3768,...,243.0,148.0,35.0,199.0,18.0,123.0,83.0,NaN,1,ok for band gap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4531,2,31,63,[113352 31 63],8,.:.,NaN,-0.3798,-0.4050,-0.4015,...,243.0,112.0,35.0,198.0,18.0,123.0,83.0,NaN,1,ok for band gap
4532,2,-7,29,[113352 -7 29],8,.:.,NaN,-0.3965,-0.4209,-0.4189,...,242.0,128.0,35.0,199.0,18.0,123.0,83.0,pass,1,ok for band gap
4533,2,20,32,[113352 20 32],8,.:.,NaN,-0.3673,-0.4128,-0.4070,...,243.0,128.0,35.0,199.0,18.0,123.0,83.0,NaN,1,ok for band gap
4534,2,35,60,[113352 35 60],8,.:.,NaN,-0.3786,-0.4056,-0.4240,...,243.0,140.0,35.0,199.0,18.0,123.0,83.0,NaN,1,ok for band gap
4535,2,4,59,[113352 4 59],8,.:.,NaN,-0.3757,-0.4155,-0.4104,...,243.0,149.0,34.0,197.0,18.0,123.0,83.0,NaN,1,ok for band gap

In [13]:
# Define a list of columns to drop
columns_to_drop = [
    'soft_bin of FT1',
    'soft_bin of FT2',
    'soft_bin',
    'BG pass/fail'
]

# Drop columns (use inplace=True to modify the original DataFrame)
# Or create a new DataFrame with processed_dataset = processed_dataset.drop(...)
initial_dataset.drop(columns=columns_to_drop, inplace=True)

In [14]:
# Rename the columns
initial_dataset.rename(columns={'x_pos': 'X', 'y_pos': 'Y'}, inplace=True)

In [15]:
# Calculate the Radius column
# The np.sqrt() function calculates the square root of each element.
initial_dataset['Radius'] = np.sqrt(initial_dataset['X']**2 + initial_dataset['Y']**2)
initial_dataset.to_pickle("data/initial_dataset.p")

#### scnarios

In [16]:
# import vars and function

from algos.algos import *
from config.config import *

In [17]:
import copy

##### preprocess_dataset

In [18]:
preprocessed_dataset = preprocess_dataset(initial_dataset)

     데이터셋 전처리 중...
     전처리 완료!

##### create_train_and_test_data

In [19]:
split_parameter = copy.deepcopy(split_parameter_default)
train_data, test_data, split_parameter_info = create_train_test_data(preprocessed_dataset, split_parameter)

##############################################################################################################################
# 3) Create Train/Test Split (훈련/테스트 데이터 분할)
##############################################################################################################################

     훈련 및 테스트 데이터셋 생성 중...
     - 분할 전 필터링 미적용.
     - Feature Generation 미적용.

     - 분할 전 훈련 데이터 클래스 분포: {0.0: 3546, 1.0: 71}
     - 샘플링 미적용

##### Use user-specified thresholds - feature selection and feature importance calculation

##### select_feature

In [20]:
feature_selector_params_var = copy.deepcopy(feature_selector_params_FeatureFilter_default)
feature_selector_params_var["filter_methods"]["apply_variance_filter"] = True
feature_selector_params_var["filter_methods"]["var_threshold"] = 0.00
feature_selection_info_var = select_feature(train_data, feature_selector_params_var)

feature_selector_params_licor = copy.deepcopy(feature_selector_params_FeatureFilter_default)
feature_selector_params_licor["filter_methods"]["apply_target_linear_corr_filter"] = True
feature_selector_params_licor["filter_methods"]["target_linear_corr_threshold"] = 0.00
feature_selection_info_licor = select_feature(train_data, feature_selector_params_licor)

feature_selector_params_xicor = copy.deepcopy(feature_selector_params_FeatureFilter_default)
feature_selector_params_xicor["filter_methods"]["apply_target_xicor_filter"] = True
feature_selector_params_xicor["filter_methods"]["target_xicor_threshold"] = 0.00
feature_selection_info_xicor = select_feature(train_data, feature_selector_params_xicor)

feature_selector_params_sfm = copy.deepcopy(feature_selector_params_sfm_default)
feature_selector_params_sfm["params"]["estimator"]["params"]["n_estimators"] = 250 # max = len(train_data.columns) - 1
feature_selector_params_sfm["params"]["threshold"] = "0*median"
feature_selection_info_sfm = select_feature(train_data, feature_selector_params_sfm)

feature_selection_infos = {
     "var" : feature_selection_info_var,
     "licor" : feature_selection_info_licor,
     "xicor" : feature_selection_info_xicor,
     "model" : feature_selection_info_sfm
}
for fileter_name, feature_selection_info in feature_selection_infos.items():
    print("# of feature:", feature_selection_info["final_feature_count"], ",  filter: ", feature_selection_info["feature_selector_name"], fileter_name)

--- 피처 선택기: FeatureFilter ---

--- 피처 필터링 시작 ---
    - 분산 필터링 후 남은 피처 수: 1401

피처 선택 결과가 'data/result/jsons\feature_selection_info_250903_073803_e1272ab5.json' 파일에 저장되었습니다.

- 최종 피처 수: 1401

--- 피처 선택기: FeatureFilter ---

--- 피처 필터링 시작 ---
    - 타겟 선형 상관관계 필터링 후 남은 피처 수: 1650

피처 선택 결과가 'data/result/jsons\feature_selection_info_250903_073803_a8a8f9ef.json' 파일에 저장되었습니다.

- 최종 피처 수: 1650

--- 피처 선택기: FeatureFilter ---

--- 피처 필터링 시작 ---
    - 타겟 Xi Cor 필터링 후 남은 피처 수: 1650

피처 선택 결과가 'data/result/jsons\feature_selection_info_250903_073803_78ad0ed6.json' 파일에 저장되었습니다.

- 최종 피처 수: 1650

--- 피처 선택기: SFM ---
--- SFM 선택기 완료 ---
남은 피처 수: 1650

피처 선택 결과가 'data/result/jsons\feature_selection_info_250903_073805_435e46a9.json' 파일에 저장되었습니다.

- 최종 피처 수: 1650
# of feature: 1401 ,  filter:  FeatureFilter var
# of feature: 1650 ,  filter:  FeatureFilter licor
# of feature: 1650 ,  filter:  FeatureFilter xicor
# of feature: 1650 ,  filter:  SFM model

In [21]:
# Summarize feature selector importance information

features_values_dfs = pd.DataFrame(
    list(train_data.columns), 
    columns=['feature_name']
)

for fileter_name, feature_selection_info in feature_selection_infos.items():
    if feature_selection_info["feature_selector_name"] == 'FeatureFilter':
        if feature_selection_info["filter_methods"]["apply_variance_filter"] == True:
            value_type = "variance"
        elif feature_selection_info["filter_methods"]["apply_target_linear_corr_filter"] == True:
            value_type = "target_linear_correlation"
        elif feature_selection_info["filter_methods"]["apply_target_xicor_filter"] == True:
            value_type = "target_xicor_correlation"
        features_values = feature_selection_info["selection_details"][value_type]["features_values_checked"]
    else : 
        value_type = "importances"
        features_values = feature_selection_info["selection_details"][value_type]

    features_values_df = pd.DataFrame(
        list(features_values.items()), 
        columns=['feature_name', feature_selection_info["feature_selector_name"]+"_"+value_type]
    )

    features_values_dfs = pd.merge(
        features_values_dfs,
        features_values_df,
        how='outer',
        left_on='feature_name',
        right_on='feature_name'
        )

In [22]:
# # Feature selection results by method: dic

feature_selection_info

{'feature_selector_name': 'SFM',
 'params': {'threshold': '0*median',
  'estimator': {'name': 'RandomForestClassifier',
   'params': {'n_estimators': 250, 'max_depth': 12}}},
 'filter_methods': 'apply_SelectFromModel_filter',
 'initial_feature_count': 1650,
 'final_feature_count': 1650,
 'final_features': ['X',
  'Y',
  'Radius',
  'AC_COIL_FACTOR of 1103959_69_1133529_YPP',
  'AC_COIL_FACTOR of 1103959_69_1133529_cp1_cp1p5',
  'AC_COIL_FACTOR of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_COIL_FACTOR of 1103959_69_1133592_RPP',
  'AC_GAIN_32 of 1103959_69_1133529_cp1',
  'AC_GAIN_32 of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_GAIN_32 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_GAIN_32 of 1103959_69_1133529_cp1p5',
  'AC_GAIN_32 of 1103959_69_1133592_QPP',
  'AC_GAIN_32 of 1103959_69_JPP',
  'AC_GAIN_33 of 1103959_69_1133529_cp1',
  'AC_GAIN_33 of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_GAIN_33 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_GAIN_33 of 1103959_69_1133529_cp1p5',
  'AC_GAIN_33 of 1103959_69_1133592_QPP',
  'AC_GAIN_33 of 1103959_69_JPP',
  'AC_ITER of 1103959_69_1133529_YPP',
  'AC_ITER of 1103959_69_1133529_cp1_cp1p5',
  'AC_ITER of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_ITER of 1103959_69_1133592_RPP',
  'AC_MATCH_FAIL_PF of 1103959_69_1133529_YPP',
  'AC_MATCH_FAIL_PF of 1103959_69_1133529_cp1_cp1p5',
  'AC_MATCH_FAIL_PF of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_MATCH_FAIL_PF of 1103959_69_1133592_RPP',
  'AC_OFFCALRES of 1103959_69_1133529_cp1',
  'AC_OFFCALRES of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_OFFCALRES of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_OFFCALRES of 1103959_69_1133529_cp1p5',
  'AC_OFFCALRES of 1103959_69_1133592_QPP',
  'AC_OFFCALRES of 1103959_69_JPP',
  'AC_OFFCALRES_PRE of 1103959_69_1133529_cp1',
  'AC_OFFCALRES_PRE of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_OFFCALRES_PRE of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_OFFCALRES_PRE of 1103959_69_1133529_cp1p5',
  'AC_OFFCALRES_PRE of 1103959_69_1133592_QPP',
  'AC_OFFCALRES_PRE of 1103959_69_JPP',
  'AC_SENSETGT of 1103959_69_1133529_cp1',
  'AC_SENSETGT of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_SENSETGT of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_SENSETGT of 1103959_69_1133529_cp1p5',
  'AC_SENSETGT of 1103959_69_1133592_QPP',
  'AC_SENSETGT of 1103959_69_JPP',
  'AC_SENSE_CAL of 1103959_69_1133529_cp1',
  'AC_SENSE_CAL of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_SENSE_CAL of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_SENSE_CAL of 1103959_69_1133529_cp1p5',
  'AC_SENSE_CAL of 1103959_69_1133592_QPP',
  'AC_SENSE_CAL of 1103959_69_JPP',
  'AC_SENSE_CLN 2 of 1103959_69_1133529_YPP',
  'AC_SENSE_CLN 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_SENSE_CLN 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_SENSE_CLN 2 of 1103959_69_1133592_RPP',
  'AC_SENSE_CLN of 1103959_69_1133529_cp1',
  'AC_SENSE_CLN of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_SENSE_CLN of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_SENSE_CLN of 1103959_69_1133529_cp1p5',
  'AC_SENSE_CLN of 1103959_69_1133592_QPP',
  'AC_SENSE_CLN of 1103959_69_JPP',
  'AC_SENSE_CLP of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_SENSE_CLP of 1103959_69_1133592_RPP',
  'AC_SENSE_CN_FG_SA of 1103959_69_1133529_cp1',
  'AC_SENSE_CN_FG_SA of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_SENSE_CN_FG_SA of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_SENSE_CN_FG_SA of 1103959_69_1133529_cp1p5',
  'AC_SENSE_CN_FG_SA of 1103959_69_1133592_QPP',
  'AC_SENSE_CN_FG_SA of 1103959_69_JPP',
  'AC_SENSE_CRN 2 of 1103959_69_1133529_YPP',
  'AC_SENSE_CRN 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_SENSE_CRN 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_SENSE_CRN 2 of 1103959_69_1133592_RPP',
  'AC_SENSE_CRN of 1103959_69_1133529_cp1',
  'AC_SENSE_CRN of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_SENSE_CRN of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_SENSE_CRN of 1103959_69_1133529_cp1p5',
  'AC_SENSE_CRN of 1103959_69_1133592_QPP',
  'AC_SENSE_CRN of 1103959_69_JPP',
  'AC_SENSE_CRP of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_SENSE_CRP of 1103959_69_1133592_RPP',
  'AC_TLIN_H2_BIAS of 1103959_69_1133529_YPP',
  'AC_TLIN_H2_BIAS of 1103959_69_1133529_cp1_cp1p5',
  'AC_TLIN_H2_BIAS of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_TLIN_H2_BIAS of 1103959_69_1133592_RPP',
  'AC_TLIN_H2_BIAS_INIT of 1103959_69_1133529_YPP',
  'AC_TLIN_H2_BIAS_INIT of 1103959_69_1133529_cp1_cp1p5',
  'AC_TLIN_H2_BIAS_INIT of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_TLIN_H2_BIAS_INIT of 1103959_69_1133592_RPP',
  'AC_TRIALS of 1103959_69_1133529_cp1',
  'AC_TRIALS of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_TRIALS of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_TRIALS of 1103959_69_1133529_cp1p5',
  'AC_TRIALS of 1103959_69_1133592_QPP',
  'AC_TRIALS of 1103959_69_JPP',
  'AC_T_H2_BIAS of 1103959_69_1133529_YPP',
  'AC_T_H2_BIAS of 1103959_69_1133529_cp1_cp1p5',
  'AC_T_H2_BIAS of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_T_H2_BIAS of 1103959_69_1133592_RPP',
  'AC_T_H2_BIAS_INIT of 1103959_69_1133529_YPP',
  'AC_T_H2_BIAS_INIT of 1103959_69_1133529_cp1_cp1p5',
  'AC_T_H2_BIAS_INIT of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_T_H2_BIAS_INIT of 1103959_69_1133592_RPP',
  'AC_VOFF_TGT of 1103959_69_1133529_cp1',
  'AC_VOFF_TGT of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_VOFF_TGT of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_VOFF_TGT of 1103959_69_1133529_cp1p5',
  'AC_VOFF_TGT of 1103959_69_1133592_QPP',
  'AC_VOFF_TGT of 1103959_69_JPP',
  'AC_VOFF_TGT_PRE of 1103959_69_1133529_cp1',
  'AC_VOFF_TGT_PRE of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_VOFF_TGT_PRE of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_VOFF_TGT_PRE of 1103959_69_1133529_cp1p5',
  'AC_VOFF_TGT_PRE of 1103959_69_1133592_QPP',
  'AC_VOFF_TGT_PRE of 1103959_69_JPP',
  'AC_VOFF_TGT_PRE_TM of 1103959_69_1133529_cp1',
  'AC_VOFF_TGT_PRE_TM of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_VOFF_TGT_PRE_TM of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_VOFF_TGT_PRE_TM of 1103959_69_1133529_cp1p5',
  'AC_VOFF_TGT_PRE_TM of 1103959_69_1133592_QPP',
  'AC_VOFF_TGT_PRE_TM of 1103959_69_JPP',
  'AC_VOUTB0 of 1103959_69_1133529_cp1',
  'AC_VOUTB0 of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_VOUTB0 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_VOUTB0 of 1103959_69_1133529_cp1p5',
  'AC_VOUTB0 of 1103959_69_1133592_QPP',
  'AC_VOUTB0 of 1103959_69_JPP',
  'AC_VOUTB0_PRE of 1103959_69_1133529_cp1',
  'AC_VOUTB0_PRE of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_VOUTB0_PRE of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_VOUTB0_PRE of 1103959_69_1133529_cp1p5',
  'AC_VOUTB0_PRE of 1103959_69_1133592_QPP',
  'AC_VOUTB0_PRE of 1103959_69_JPP',
  'AC_V_AFE_5_8_8_SENSL of 1103959_69_1133529_YPP',
  'AC_V_AFE_5_8_8_SENSL of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_5_8_8_SENSL of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_5_8_8_SENSL of 1103959_69_1133592_RPP',
  'AC_V_AFE_5_8_8_SENSR of 1103959_69_1133529_YPP',
  'AC_V_AFE_5_8_8_SENSR of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_5_8_8_SENSR of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_5_8_8_SENSR of 1103959_69_1133592_RPP',
  'AC_V_AFE_5_8_8_SENSR_INIT of 1103959_69_1133529_YPP',
  'AC_V_AFE_5_8_8_SENSR_INIT of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_5_8_8_SENSR_INIT of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_5_8_8_SENSR_INIT of 1103959_69_1133592_RPP',
  'AC_V_AFE_CLN_5_8_8_I0 2 of 1103959_69_1133529_YPP',
  'AC_V_AFE_CLN_5_8_8_I0 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_CLN_5_8_8_I0 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CLN_5_8_8_I0 2 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CLN_5_8_8_I0 of 1103959_69_1133529_cp1',
  'AC_V_AFE_CLN_5_8_8_I0 of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CLN_5_8_8_I0 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CLN_5_8_8_I0 of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CLN_5_8_8_I0 of 1103959_69_1133592_QPP',
  'AC_V_AFE_CLN_5_8_8_I0 of 1103959_69_JPP',
  'AC_V_AFE_CLN_5_8_8_I0_RAW 2 of 1103959_69_1133529_YPP',
  'AC_V_AFE_CLN_5_8_8_I0_RAW 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_CLN_5_8_8_I0_RAW 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CLN_5_8_8_I0_RAW 2 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CLN_5_8_8_I0_RAW of 1103959_69_1133529_cp1',
  'AC_V_AFE_CLN_5_8_8_I0_RAW of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CLN_5_8_8_I0_RAW of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CLN_5_8_8_I0_RAW of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CLN_5_8_8_I0_RAW of 1103959_69_1133592_QPP',
  'AC_V_AFE_CLN_5_8_8_I0_RAW of 1103959_69_JPP',
  'AC_V_AFE_CLN_5_8_8_I0_VSS 2 of 1103959_69_1133529_YPP',
  'AC_V_AFE_CLN_5_8_8_I0_VSS 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_CLN_5_8_8_I0_VSS 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CLN_5_8_8_I0_VSS 2 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CLN_5_8_8_I0_VSS of 1103959_69_1133529_cp1',
  'AC_V_AFE_CLN_5_8_8_I0_VSS of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CLN_5_8_8_I0_VSS of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CLN_5_8_8_I0_VSS of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CLN_5_8_8_I0_VSS of 1103959_69_1133592_QPP',
  'AC_V_AFE_CLN_5_8_8_I0_VSS of 1103959_69_JPP',
  'AC_V_AFE_CLN_5_8_8_P_F 2 of 1103959_69_1133529_YPP',
  'AC_V_AFE_CLN_5_8_8_P_F 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_CLN_5_8_8_P_F 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CLN_5_8_8_P_F 2 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CLN_5_8_8_P_F of 1103959_69_1133529_cp1',
  'AC_V_AFE_CLN_5_8_8_P_F of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CLN_5_8_8_P_F of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CLN_5_8_8_P_F of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CLN_5_8_8_P_F of 1103959_69_1133592_QPP',
  'AC_V_AFE_CLN_5_8_8_P_F of 1103959_69_JPP',
  'AC_V_AFE_CLN_5_8_8_VSS 2 of 1103959_69_1133529_YPP',
  'AC_V_AFE_CLN_5_8_8_VSS 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_CLN_5_8_8_VSS 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CLN_5_8_8_VSS 2 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CLN_5_8_8_VSS of 1103959_69_1133529_cp1',
  'AC_V_AFE_CLN_5_8_8_VSS of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CLN_5_8_8_VSS of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CLN_5_8_8_VSS of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CLN_5_8_8_VSS of 1103959_69_1133592_QPP',
  'AC_V_AFE_CLN_5_8_8_VSS of 1103959_69_JPP',
  'AC_V_AFE_CLP_5_8_8_I0 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CLP_5_8_8_I0 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CLP_5_8_8_I0_RAW of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CLP_5_8_8_I0_RAW of 1103959_69_1133592_RPP',
  'AC_V_AFE_CLP_5_8_8_I0_VSS of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CLP_5_8_8_I0_VSS of 1103959_69_1133592_RPP',
  'AC_V_AFE_CLP_5_8_8_P_F of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CLP_5_8_8_P_F of 1103959_69_1133592_RPP',
  'AC_V_AFE_CLP_5_8_8_VSS of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CLP_5_8_8_VSS of 1103959_69_1133592_RPP',
  'AC_V_AFE_CN_5_8_8_I0 JPP',
  'AC_V_AFE_CN_5_8_8_I0 QPP',
  'AC_V_AFE_CN_5_8_8_I0 RPP',
  'AC_V_AFE_CN_5_8_8_I0 YPP',
  'AC_V_AFE_CN_5_8_8_I0 cp1',
  'AC_V_AFE_CN_5_8_8_I0 cp1p5',
  'AC_V_AFE_CN_FG_SA_I0 of 1103959_69_1133529_cp1',
  'AC_V_AFE_CN_FG_SA_I0 of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CN_FG_SA_I0 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CN_FG_SA_I0 of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CN_FG_SA_I0 of 1103959_69_1133592_QPP',
  'AC_V_AFE_CN_FG_SA_I0 of 1103959_69_JPP',
  'AC_V_AFE_CN_FG_SA_P_F of 1103959_69_1133529_cp1',
  'AC_V_AFE_CN_FG_SA_P_F of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CN_FG_SA_P_F of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CN_FG_SA_P_F of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CN_FG_SA_P_F of 1103959_69_1133592_QPP',
  'AC_V_AFE_CN_FG_SA_P_F of 1103959_69_JPP',
  'AC_V_AFE_CN_TGT_I0 of 1103959_69_1133529_cp1',
  'AC_V_AFE_CN_TGT_I0 of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CN_TGT_I0 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CN_TGT_I0 of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CN_TGT_I0 of 1103959_69_1133592_QPP',
  'AC_V_AFE_CN_TGT_I0 of 1103959_69_JPP',
  'AC_V_AFE_CRN_5_8_8_I0 2 of 1103959_69_1133529_YPP',
  'AC_V_AFE_CRN_5_8_8_I0 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_CRN_5_8_8_I0 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CRN_5_8_8_I0 2 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CRN_5_8_8_I0 of 1103959_69_1133529_cp1',
  'AC_V_AFE_CRN_5_8_8_I0 of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CRN_5_8_8_I0 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CRN_5_8_8_I0 of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CRN_5_8_8_I0 of 1103959_69_1133592_QPP',
  'AC_V_AFE_CRN_5_8_8_I0 of 1103959_69_JPP',
  'AC_V_AFE_CRN_5_8_8_I0_RAW 2 of 1103959_69_1133529_YPP',
  'AC_V_AFE_CRN_5_8_8_I0_RAW 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_CRN_5_8_8_I0_RAW 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CRN_5_8_8_I0_RAW 2 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CRN_5_8_8_I0_RAW of 1103959_69_1133529_cp1',
  'AC_V_AFE_CRN_5_8_8_I0_RAW of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CRN_5_8_8_I0_RAW of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CRN_5_8_8_I0_RAW of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CRN_5_8_8_I0_RAW of 1103959_69_1133592_QPP',
  'AC_V_AFE_CRN_5_8_8_I0_RAW of 1103959_69_JPP',
  'AC_V_AFE_CRN_5_8_8_I0_VSS 2 of 1103959_69_1133529_YPP',
  'AC_V_AFE_CRN_5_8_8_I0_VSS 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_CRN_5_8_8_I0_VSS 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CRN_5_8_8_I0_VSS 2 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CRN_5_8_8_I0_VSS of 1103959_69_1133529_cp1',
  'AC_V_AFE_CRN_5_8_8_I0_VSS of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CRN_5_8_8_I0_VSS of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CRN_5_8_8_I0_VSS of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CRN_5_8_8_I0_VSS of 1103959_69_1133592_QPP',
  'AC_V_AFE_CRN_5_8_8_I0_VSS of 1103959_69_JPP',
  'AC_V_AFE_CRN_5_8_8_P_F 2 of 1103959_69_1133529_YPP',
  'AC_V_AFE_CRN_5_8_8_P_F 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_CRN_5_8_8_P_F 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CRN_5_8_8_P_F 2 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CRN_5_8_8_P_F of 1103959_69_1133529_cp1',
  'AC_V_AFE_CRN_5_8_8_P_F of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CRN_5_8_8_P_F of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CRN_5_8_8_P_F of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CRN_5_8_8_P_F of 1103959_69_1133592_QPP',
  'AC_V_AFE_CRN_5_8_8_P_F of 1103959_69_JPP',
  'AC_V_AFE_CRN_5_8_8_VSS 2 of 1103959_69_1133529_YPP',
  'AC_V_AFE_CRN_5_8_8_VSS 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_AFE_CRN_5_8_8_VSS 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CRN_5_8_8_VSS 2 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CRN_5_8_8_VSS of 1103959_69_1133529_cp1',
  'AC_V_AFE_CRN_5_8_8_VSS of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_AFE_CRN_5_8_8_VSS of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_AFE_CRN_5_8_8_VSS of 1103959_69_1133529_cp1p5',
  'AC_V_AFE_CRN_5_8_8_VSS of 1103959_69_1133592_QPP',
  'AC_V_AFE_CRN_5_8_8_VSS of 1103959_69_JPP',
  'AC_V_AFE_CRP_5_8_8_I0 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CRP_5_8_8_I0 of 1103959_69_1133592_RPP',
  'AC_V_AFE_CRP_5_8_8_I0_RAW of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CRP_5_8_8_I0_RAW of 1103959_69_1133592_RPP',
  'AC_V_AFE_CRP_5_8_8_I0_VSS of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CRP_5_8_8_I0_VSS of 1103959_69_1133592_RPP',
  'AC_V_AFE_CRP_5_8_8_P_F of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CRP_5_8_8_P_F of 1103959_69_1133592_RPP',
  'AC_V_AFE_CRP_5_8_8_VSS of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_AFE_CRP_5_8_8_VSS of 1103959_69_1133592_RPP',
  'AC_V_GAIN_AFE_CLN_5_8_8 2 of 1103959_69_1133529_YPP',
  'AC_V_GAIN_AFE_CLN_5_8_8 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_GAIN_AFE_CLN_5_8_8 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_GAIN_AFE_CLN_5_8_8 2 of 1103959_69_1133592_RPP',
  'AC_V_GAIN_AFE_CLN_5_8_8 of 1103959_69_1133529_cp1',
  'AC_V_GAIN_AFE_CLN_5_8_8 of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_GAIN_AFE_CLN_5_8_8 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_GAIN_AFE_CLN_5_8_8 of 1103959_69_1133529_cp1p5',
  'AC_V_GAIN_AFE_CLN_5_8_8 of 1103959_69_1133592_QPP',
  'AC_V_GAIN_AFE_CLN_5_8_8 of 1103959_69_JPP',
  'AC_V_GAIN_AFE_CLN_5_8_8_RAW 2 of 1103959_69_1133529_YPP',
  'AC_V_GAIN_AFE_CLN_5_8_8_RAW 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_GAIN_AFE_CLN_5_8_8_RAW 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_GAIN_AFE_CLN_5_8_8_RAW 2 of 1103959_69_1133592_RPP',
  'AC_V_GAIN_AFE_CLN_5_8_8_RAW of 1103959_69_1133529_cp1',
  'AC_V_GAIN_AFE_CLN_5_8_8_RAW of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_GAIN_AFE_CLN_5_8_8_RAW of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_GAIN_AFE_CLN_5_8_8_RAW of 1103959_69_1133529_cp1p5',
  'AC_V_GAIN_AFE_CLN_5_8_8_RAW of 1103959_69_1133592_QPP',
  'AC_V_GAIN_AFE_CLN_5_8_8_RAW of 1103959_69_JPP',
  'AC_V_GAIN_AFE_CLP_5_8_8 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_GAIN_AFE_CLP_5_8_8 of 1103959_69_1133592_RPP',
  'AC_V_GAIN_AFE_CLP_5_8_8_RAW of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_GAIN_AFE_CLP_5_8_8_RAW of 1103959_69_1133592_RPP',
  'AC_V_GAIN_AFE_CN_FG_SA of 1103959_69_1133529_cp1',
  'AC_V_GAIN_AFE_CN_FG_SA of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_GAIN_AFE_CN_FG_SA of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_GAIN_AFE_CN_FG_SA of 1103959_69_1133529_cp1p5',
  'AC_V_GAIN_AFE_CN_FG_SA of 1103959_69_1133592_QPP',
  'AC_V_GAIN_AFE_CN_FG_SA of 1103959_69_JPP',
  'AC_V_GAIN_AFE_CRN_5_8_8 2 of 1103959_69_1133529_YPP',
  'AC_V_GAIN_AFE_CRN_5_8_8 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_GAIN_AFE_CRN_5_8_8 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_GAIN_AFE_CRN_5_8_8 2 of 1103959_69_1133592_RPP',
  'AC_V_GAIN_AFE_CRN_5_8_8 of 1103959_69_1133529_cp1',
  'AC_V_GAIN_AFE_CRN_5_8_8 of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_GAIN_AFE_CRN_5_8_8 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_GAIN_AFE_CRN_5_8_8 of 1103959_69_1133529_cp1p5',
  'AC_V_GAIN_AFE_CRN_5_8_8 of 1103959_69_1133592_QPP',
  'AC_V_GAIN_AFE_CRN_5_8_8 of 1103959_69_JPP',
  'AC_V_GAIN_AFE_CRN_5_8_8_RAW 2 of 1103959_69_1133529_YPP',
  'AC_V_GAIN_AFE_CRN_5_8_8_RAW 2 of 1103959_69_1133529_cp1_cp1p5',
  'AC_V_GAIN_AFE_CRN_5_8_8_RAW 2 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_GAIN_AFE_CRN_5_8_8_RAW 2 of 1103959_69_1133592_RPP',
  'AC_V_GAIN_AFE_CRN_5_8_8_RAW of 1103959_69_1133529_cp1',
  'AC_V_GAIN_AFE_CRN_5_8_8_RAW of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AC_V_GAIN_AFE_CRN_5_8_8_RAW of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AC_V_GAIN_AFE_CRN_5_8_8_RAW of 1103959_69_1133529_cp1p5',
  'AC_V_GAIN_AFE_CRN_5_8_8_RAW of 1103959_69_1133592_QPP',
  'AC_V_GAIN_AFE_CRN_5_8_8_RAW of 1103959_69_JPP',
  'AC_V_GAIN_AFE_CRP_5_8_8 of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_GAIN_AFE_CRP_5_8_8 of 1103959_69_1133592_RPP',
  'AC_V_GAIN_AFE_CRP_5_8_8_RAW of 1103959_69_1133529_cp1_cp1p5_YPP_QPP',
  'AC_V_GAIN_AFE_CRP_5_8_8_RAW of 1103959_69_1133592_RPP',
  'AG_AFE_GAIN_10_1_2_PF of 1103959_69_1133529_cp1',
  'AG_AFE_GAIN_10_1_2_PF of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AG_AFE_GAIN_10_1_2_PF of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AG_AFE_GAIN_10_1_2_PF of 1103959_69_1133529_cp1p5',
  'AG_AFE_GAIN_10_1_2_PF of 1103959_69_1133592_QPP',
  'AG_AFE_GAIN_10_1_2_PF of 1103959_69_JPP',
  'AG_AFE_GAIN_11_2_1_PF of 1103959_69_1133529_cp1',
  'AG_AFE_GAIN_11_2_1_PF of 1103959_69_1133529_cp1_cp1p5_YPP',
  'AG_AFE_GAIN_11_2_1_PF of 1103959_69_1133529_cp1_cp1p5_YPP_QPP_RPP',
  'AG_AFE_GAIN_11_2_1_PF of 1103959_69_1133529_cp1p5',
  'AG_AFE_GAIN_11_2_1_PF of 1103959_69_1133592_QPP',
  'AG_AFE_GAIN_11_2_1_PF of 1103959_69_JPP',
  'AG_AFE_GAIN_12_2_1_2C_PF of 1103959_69_1133529_cp1',
  'AG_AFE_GAIN_12_2_1_2C_PF of 1103959_69_1133529_cp1_cp1p5_YPP',

In [23]:
# # Feature selection results summary data by method: df

features_values_dfs

,feature_name,FeatureFilter_variance,FeatureFilter_target_linear_correlation,FeatureFilter_target_xicor_correlation,SFM_importances
0,AC_COIL_FACTOR of 1103959_69_1133529_YPP,2.951574e-33,0.021211,0.255277,0.000000
1,AC_COIL_FACTOR of 1103959_69_1133529_cp1_cp1p5,2.951574e-33,0.021211,0.255277,0.000000
2,AC_COIL_FACTOR of 1103959_69_1133529_cp1_cp1p5...,2.951574e-33,0.021211,0.255277,0.000000
3,AC_COIL_FACTOR of 1103959_69_1133592_RPP,2.951574e-33,0.021211,0.255277,0.000000
4,AC_GAIN_32 of 1103959_69_1133529_cp1,0.000000e+00,NaN,0.456388,0.000000
...,...,...,...,...,...
1646,Zb_V_OBVOL_VSS_L of 1103959_69_1133529_cp1_cp1...,1.000277e+00,0.017764,0.505893,0.000395
1647,Zb_V_OBVOL_VSS_L of 1103959_69_1133529_cp1p5,1.000277e+00,0.026030,0.396025,0.000935
1648,Zb_V_OBVOL_VSS_L of 1103959_69_1133592_QPP,1.000277e+00,0.001384,0.447422,0.000143
1649,Zb_V_OBVOL_VSS_L of 1103959_69_JPP,1.000277e+00,0.067453,0.604254,0.000389
1650,band gap dpat_ok for band gap,2.098254e-01,0.016280,0.460164,0.000105

In [24]:
# feature select test : pipeline
## Apply the selected feature set feature_selection_info['final_features'] list to the modeling pipeline and return the modeling results

def pl_fs_test(
        train_data,
        feature_selection_info,
        train_parameters,
        test_data
        ):
    
    trained_model, feature_importance, train_parameters_info = train_model_rf_cv(train_data.copy(), feature_selection_info, train_parameters)
    forecast_dataset, shap_values_random_forest = forecast(test_data, trained_model, feature_selection_info)
    train_dataset_proba, best_threshold = find_best_threshold(trained_model, train_data.copy(), feature_selection_info)
    roc_data, auc_score = roc_from_scratch(forecast_dataset, test_data, partitions=100)
    train_dataset_metrics = create_metrics_on_train(train_dataset_proba, best_threshold)
    metrics = create_metrics(forecast_dataset, test_data, auc_score, best_threshold)
    results = create_results(forecast_dataset, test_data, best_threshold)
    
    return \
        trained_model, \
        feature_importance, \
        forecast_dataset, \
        train_dataset_proba, \
        best_threshold, \
        roc_data, \
        auc_score, \
        train_dataset_metrics, \
        metrics, \
        results

##### Use user-specified thresholds - feature selection > performance check: Use a simple model pipeline

In [25]:
# Apply the model based on the specified threshold and summarize the results
# feature select test - submit and summary result

usr_pl_fs_test_result_ftpn_df = pd.DataFrame()
usr_pl_fs_test_result_features_values_dfs = pd.DataFrame(
    list(train_data.columns), 
    columns=['feature_name']
)

for fileter_name, feature_selection_info in feature_selection_infos.items():
    trained_model, \
    feature_importance, \
    forecast_dataset, \
    train_dataset_proba, \
    best_threshold, \
    roc_data, \
    auc_score, \
    train_dataset_metrics, \
    metrics, \
    results \
    = \
    pl_fs_test(
            train_data,
            feature_selection_info,
            train_parameters_list_default["rf_cv"],
            test_data
            )

    dict_ftpn = metrics["dict_ftpn"]
    
    new_row = {
        'fn': dict_ftpn.get('fn'),
        'fp': dict_ftpn.get('fp'),
        'tn': dict_ftpn.get('tn'),
        'tp': dict_ftpn.get('tp'),
        'feature_selector_name' : feature_selection_info["feature_selector_name"],
        'filter_methods' : feature_selection_info["filter_methods"],
        'initial_feature_count' : feature_selection_info["initial_feature_count"],
        'final_feature_count' : feature_selection_info["final_feature_count"],
        'feature_selection_info_json_path' : feature_selection_info["feature_selection_info_json_path"]
    }
    
    usr_pl_fs_test_result_ftpn_df = pd.concat([usr_pl_fs_test_result_ftpn_df, pd.DataFrame([new_row])], ignore_index=True)

    if feature_selection_info["feature_selector_name"] == 'FeatureFilter':
        if feature_selection_info["filter_methods"]["apply_variance_filter"] == True:
            value_type = "variance"
        elif feature_selection_info["filter_methods"]["apply_target_linear_corr_filter"] == True:
            value_type = "target_linear_correlation"
        elif feature_selection_info["filter_methods"]["apply_target_xicor_filter"] == True:
            value_type = "target_xicor_correlation"
        features_values = feature_selection_info["selection_details"][value_type]["features_values_checked"]
    else : 
        value_type = "importances"
        features_values = feature_selection_info["selection_details"][value_type]

    features_values_df = pd.DataFrame(
        list(features_values.items()), 
        columns=['feature_name', feature_selection_info["feature_selector_name"]+"_"+value_type]
    )

    usr_pl_fs_test_result_features_values_dfs = pd.merge(
        usr_pl_fs_test_result_features_values_dfs,
        features_values_df,
        how='outer',
        left_on='feature_name',
        right_on='feature_name'
        )

      Training the Random Forest model with cross-validation & hyperparameter tuning...

Fitting 3 folds for each of 18 candidates, totalling 54 fits

    Best parameters found: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 50}
    Best F2 (class=1) score (CV): 0.2258

      Forecasting the test dataset...
      Forecasting done!
Best threshold for F2 score: 0.7172 with F2 score: 0.6153
      Calculation of the ROC curve...
      Calculation done
      Scoring...
      Scoring done

      Creating the metrics...
      Training the Random Forest model with cross-validation & hyperparameter tuning...

Fitting 3 folds for each of 18 candidates, totalling 54 fits

    Best parameters found: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 20}
    Best F2 (class=1) score (CV): 0.2240

      Forecasting the test dataset...
      Forecasting done!
Best threshold for F2 score: 0.6970 with F2 score: 0.5909
      Calculation of the ROC curve...
      Calculation done
      Scoring...
      Scoring done

      Creating the metrics...
      Training the Random Forest model with cross-validation & hyperparameter tuning...

Fitting 3 folds for each of 18 candidates, totalling 54 fits

    Best parameters found: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 20}
    Best F2 (class=1) score (CV): 0.2240

      Forecasting the test dataset...
      Forecasting done!
Best threshold for F2 score: 0.6970 with F2 score: 0.5909
      Calculation of the ROC curve...
      Calculation done
      Scoring...
      Scoring done

      Creating the metrics...
      Training the Random Forest model with cross-validation & hyperparameter tuning...

Fitting 3 folds for each of 18 candidates, totalling 54 fits

    Best parameters found: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 20}
    Best F2 (class=1) score (CV): 0.2240

      Forecasting the test dataset...
      Forecasting done!
Best threshold for F2 score: 0.6970 with F2 score: 0.5909
      Calculation of the ROC curve...
      Calculation done
      Scoring...
      Scoring done

      Creating the metrics...

In [26]:
# Model performance summary of the feature selection set - based on user feature selection threshold

usr_pl_fs_test_result_ftpn_df

,fn,fp,tn,tp,feature_selector_name,filter_methods,initial_feature_count,final_feature_count,feature_selection_info_json_path
0,5,180,707,13,FeatureFilter,"{'apply_variance_filter': True, 'var_threshold...",1650,1401,data/result/jsons\feature_selection_info_25090...
1,6,184,703,12,FeatureFilter,"{'apply_variance_filter': False, 'var_threshol...",1650,1650,data/result/jsons\feature_selection_info_25090...
2,6,184,703,12,FeatureFilter,"{'apply_variance_filter': False, 'var_threshol...",1650,1650,data/result/jsons\feature_selection_info_25090...
3,6,184,703,12,SFM,apply_SelectFromModel_filter,1650,1650,data/result/jsons\feature_selection_info_25090...

In [27]:
# Model performance summary of the feature selection set + applied columns from user feature selection threshold (for reference)

usr_pl_fs_test_result_features_values_dfs

,feature_name,FeatureFilter_variance,FeatureFilter_target_linear_correlation,FeatureFilter_target_xicor_correlation,SFM_importances
0,AC_COIL_FACTOR of 1103959_69_1133529_YPP,2.951574e-33,0.021211,0.255277,0.000000
1,AC_COIL_FACTOR of 1103959_69_1133529_cp1_cp1p5,2.951574e-33,0.021211,0.255277,0.000000
2,AC_COIL_FACTOR of 1103959_69_1133529_cp1_cp1p5...,2.951574e-33,0.021211,0.255277,0.000000
3,AC_COIL_FACTOR of 1103959_69_1133592_RPP,2.951574e-33,0.021211,0.255277,0.000000
4,AC_GAIN_32 of 1103959_69_1133529_cp1,0.000000e+00,NaN,0.456388,0.000000
...,...,...,...,...,...
1646,Zb_V_OBVOL_VSS_L of 1103959_69_1133529_cp1_cp1...,1.000277e+00,0.017764,0.505893,0.000395
1647,Zb_V_OBVOL_VSS_L of 1103959_69_1133529_cp1p5,1.000277e+00,0.026030,0.396025,0.000935
1648,Zb_V_OBVOL_VSS_L of 1103959_69_1133592_QPP,1.000277e+00,0.001384,0.447422,0.000143
1649,Zb_V_OBVOL_VSS_L of 1103959_69_JPP,1.000277e+00,0.067453,0.604254,0.000389
1650,band gap dpat_ok for band gap,2.098254e-01,0.016280,0.460164,0.000105

##### Use feature importance information - optimal selection > performance check: Use a simple model pipeline

###### The optimal selection method uses the XGBClassifier model and GridSearchCV for searching for optimal values

In [28]:
feature_importance_df = features_values_dfs.copy()

In [29]:
### Apply

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import fbeta_score, make_scorer, confusion_matrix
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier
import uuid

In [30]:
# train_data

In [31]:
# Select the target as the rightmost column
target_df = train_data.iloc[:, -1]
# The rest of the columns are features
features_df = train_data.iloc[:, :-1]

X_train, X_test, y_train, y_test = train_test_split(features_df, target_df, test_size=0.2, random_state=42)

In [32]:
# run_optimization_for_feature_importance : a function to select features based on a specific importance column and find the optimal model

def run_optimization_for_feature_importance(train_data, target_data, feature_importance_df, importance_column, k_percentiles):
    """
    A function to select features based on a specific importance column and find the optimal model.
    
    Parameters:
    - train_data (pd.DataFrame): Training data
    - target_data (pd.Series): Target data
    - feature_importance_df (pd.DataFrame): DataFrame containing feature importance information
    - importance_column (str): The column name to determine the importance rank
    - k_percentiles (list): List of candidate percentiles for the number of features to select (e.g., [0.05, 0.1, 0.25, 0.5])

    Returns:
    - pd.DataFrame: Optimized feature importance information
    - pd.DataFrame: Model performance summary information
    """
    f2_scorer = make_scorer(fbeta_score, beta=2.0)
    
    # Select the top K features based on the values in the importance column
    sorted_features = feature_importance_df.sort_values(
        by=importance_column, ascending=False
    )['feature_name']
    
    # Convert percentiles to the actual number of features
    n_features_total = len(sorted_features)
    k_values = [max(1, int(n_features_total * p)) for p in k_percentiles]
    
    best_k = k_values[0]
    best_score = -1.0
    best_pipeline = None
    selected_feature_list = []
    # ⭐️ Variable to store the optimal percentile value
    best_k_percentile = k_percentiles[0]

    for i, k in enumerate(k_values):
        top_k_features = sorted_features.head(k).tolist()
        
        # Prepare the dataset with only the optimal features
        X_train_filtered = train_data[top_k_features]
        
        # Model training pipeline (direct feature selection instead of SelectKBest)
        pipeline = Pipeline([
            ('model', XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss'))
        ])
        
        param_grid = {
            'model__n_estimators': [50, 100],
            'model__max_depth': [3, 5]
        }
        
        grid_search = GridSearchCV(pipeline, param_grid, cv=3, scoring=f2_scorer, n_jobs=-1)
        grid_search.fit(X_train_filtered, target_data)

        # Evaluate the performance for the current K
        if grid_search.best_score_ > best_score:
            best_score = grid_search.best_score_
            best_k = k
            best_pipeline = grid_search.best_estimator_
            selected_feature_list = top_k_features
            # ⭐️ Update the best percentile
            best_k_percentile = k_percentiles[i]

    # Generate feature importance and performance information for the optimal model
    best_xgb_model = best_pipeline.named_steps['model']
    
    feature_info = pd.DataFrame({
        'feature_name': train_data.columns
    })
    feature_info['is_selected'] = feature_info['feature_name'].isin(selected_feature_list)
    feature_info['importance_column'] = importance_column
    feature_importances = {name: 0 for name in train_data.columns}
    
    # Assign importance scores only to the selected features
    for i, importance in enumerate(best_xgb_model.feature_importances_):
        if i < len(selected_feature_list):
            feature_importances[selected_feature_list[i]] = importance
        
    feature_info['importance_score'] = feature_info['feature_name'].map(feature_importances)
    feature_info['feature_value_by_importance_column'] = feature_info['feature_name'].map(
        feature_importance_df.set_index('feature_name')[importance_column]
    )

    # Final performance evaluation with the test data
    y_pred = best_pipeline.predict(X_test[selected_feature_list])
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

    performance_summary = pd.DataFrame([{
        'fn': fn,
        'fp': fp,
        'tn': tn,
        'tp': tp,
        'feature_selector_name': importance_column,
        'initial_feature_count': X_train.shape[1],
        'final_feature_count': len(selected_feature_list),
        'f2_score': fbeta_score(y_test, y_pred, beta=2.0),
        'importance_column': importance_column,
        # ⭐️ Add the optimal percentile column
        'best_k_percentile': best_k_percentile
    }])

    return feature_info, performance_summary

In [ ]:
# Repeat optimization for each importance column and accumulate results
# Save the importance column names from the 2nd column onwards, excluding the feature name column
importance_cols = feature_importance_df.columns[1:].tolist()

# ⭐️ Change to a list of percentile candidates: defined by the user
k_percentiles = [0.05, 0.1, 0.25, 0.5, 0.75, 0.8, 0.85, 0.9]

all_feature_infos = []
all_performance_summaries = []

for col in importance_cols:
    print(f"\n--- Running optimization based on {col} column ---")
    feat_info, perf_summary = run_optimization_for_feature_importance(
        X_train, y_train, feature_importance_df, col, k_percentiles
    )
    all_feature_infos.append(feat_info)
    all_performance_summaries.append(perf_summary)

final_feature_info_df = pd.concat(all_feature_infos, ignore_index=True)
final_feature_performance_summary_df = pd.concat(all_performance_summaries, ignore_index=True)

# 4. Print results and save to CSV
print("\n--- Final accumulated feature importance information ---")
print(final_feature_info_df.head(10))
final_feature_info_df.to_csv('final_feature_info.csv', index=False)

print("\n--- Final accumulated model performance summary ---")
print(final_feature_performance_summary_df)
final_feature_performance_summary_df.to_csv('final_feature_performance_summary.csv', index=False)

--- Running optimization based on FeatureFilter_variance column ---

--- Running optimization based on FeatureFilter_target_linear_correlation column ---

--- Running optimization based on FeatureFilter_target_xicor_correlation column ---

--- Running optimization based on SFM_importances column ---

In [ ]:
# Automatic (optimal) feature selection result data: df
final_feature_info_df

,feature_name,is_selected,importance_column,importance_score,feature_value_by_importance_column
0,X,True,FeatureFilter_variance,0.000000,1.000277e+00
1,Y,True,FeatureFilter_variance,0.007534,1.000277e+00
2,Radius,True,FeatureFilter_variance,0.003558,1.000277e+00
3,AC_COIL_FACTOR of 1103959_69_1133529_YPP,False,FeatureFilter_variance,0.000000,2.951574e-33
4,AC_COIL_FACTOR of 1103959_69_1133529_cp1_cp1p5,False,FeatureFilter_variance,0.000000,2.951574e-33
...,...,...,...,...,...
6595,FAILING_BINOUTS(1) of 1103959_69_JPP_GbGbSbSbPoPo,False,SFM_importances,0.000000,7.015850e-05
6596,FAILING_BINOUTS(1) of 1103959_69_JPP_GbPoPo,False,SFM_importances,0.000000,0.000000e+00
6597,FAILING_BINOUTS(1) of 1103959_69_JPP_PoPo,False,SFM_importances,0.000000,6.139330e-07
6598,FAILING_BINOUTS(1) of 1103959_69_JPP_SbPoPo,False,SFM_importances,0.000000,0.000000e+00
6599,band gap dpat_ok for band gap,False,SFM_importances,0.000000,1.045029e-04

In [ ]:
# Automatic (optimal) feature selection result data summary: df
final_feature_performance_summary_df

,fn,fp,tn,tp,feature_selector_name,initial_feature_count,final_feature_count,f2_score,importance_column,best_k_percentile
0,14,7,703,0,FeatureFilter_variance,1650,1320,0.0,FeatureFilter_variance,0.8
1,14,7,703,0,FeatureFilter_target_linear_correlation,1650,165,0.0,FeatureFilter_target_linear_correlation,0.1
2,14,7,703,0,FeatureFilter_target_xicor_correlation,1650,1485,0.0,FeatureFilter_target_xicor_correlation,0.9
3,14,6,704,0,SFM_importances,1650,825,0.0,SFM_importances,0.5

##### Use feature importance information - optimal selection > performance check: Use a simple model pipeline

In [ ]:
# Automatic (optimal) feature selection result data: df
final_feature_info_df

,feature_name,is_selected,importance_column,importance_score,feature_value_by_importance_column
0,X,True,FeatureFilter_variance,0.000000,1.000277e+00
1,Y,True,FeatureFilter_variance,0.007534,1.000277e+00
2,Radius,True,FeatureFilter_variance,0.003558,1.000277e+00
3,AC_COIL_FACTOR of 1103959_69_1133529_YPP,False,FeatureFilter_variance,0.000000,2.951574e-33
4,AC_COIL_FACTOR of 1103959_69_1133529_cp1_cp1p5,False,FeatureFilter_variance,0.000000,2.951574e-33
...,...,...,...,...,...
6595,FAILING_BINOUTS(1) of 1103959_69_JPP_GbGbSbSbPoPo,False,SFM_importances,0.000000,7.015850e-05
6596,FAILING_BINOUTS(1) of 1103959_69_JPP_GbPoPo,False,SFM_importances,0.000000,0.000000e+00
6597,FAILING_BINOUTS(1) of 1103959_69_JPP_PoPo,False,SFM_importances,0.000000,6.139330e-07
6598,FAILING_BINOUTS(1) of 1103959_69_JPP_SbPoPo,False,SFM_importances,0.000000,0.000000e+00
6599,band gap dpat_ok for band gap,False,SFM_importances,0.000000,1.045029e-04

In [ ]:
# Prepare performance check pipeline input: feature_selection_results
feature_selection_results = {}

# Iterate line by line
for idx, row in final_feature_performance_summary_df.iterrows():
    feature_selection_result = {}
    feature_selection_result["feature_selector_idx"] = idx
    feature_selection_result["feature_selector_name"] = row['feature_selector_name']
    feature_selection_result["initial_feature_count"] = row['initial_feature_count']
    feature_selection_result["final_feature_count"] = row['final_feature_count']
    feature_selection_result.setdefault("Params", {})["f2_score"] = row['f2_score']
    feature_selection_result.setdefault("Params", {})["best_k_percentile"] = row['best_k_percentile']
    
    feature_name_list = final_feature_info_df[
        (final_feature_info_df["importance_column"] == row['feature_selector_name']) &
        (final_feature_info_df["is_selected"] == True)
    ]["feature_name"].tolist()
    feature_selection_result["final_features"] = feature_name_list

    feature_selection_results[idx] = feature_selection_result

In [ ]:
# final_feature_performance_summary_df

In [ ]:
# feature_selection_results

In [ ]:
# Optimal feature set performance check
# feature select test - submit and summary result

trained_model_set = {}
feature_importance_set = pd.DataFrame()
forecast_dataset_set = pd.DataFrame()
train_dataset_proba_set = pd.DataFrame()
best_threshold_set = pd.DataFrame()
roc_data_set = pd.DataFrame()
auc_score_set = pd.DataFrame()
train_dataset_metrics_set = pd.DataFrame()
metrics_set = pd.DataFrame()
results_set = pd.DataFrame()

opt_pl_fs_test_result_ftpn_df = pd.DataFrame()
opt_pl_fs_test_result_features_values_dfs = pd.DataFrame(
    list(train_data.columns), 
    columns=['feature_name']
)

for feature_selector_idx, feature_selection_info in feature_selection_results.items():
    trained_model, \
    feature_importance, \
    forecast_dataset, \
    train_dataset_proba, \
    best_threshold, \
    roc_data, \
    auc_score, \
    train_dataset_metrics, \
    metrics, \
    results \
    = \
    pl_fs_test(
            train_data,
            feature_selection_info,
            train_parameters_list_default["rf_cv"],
            test_data
            )

    trained_model_set[feature_selector_idx] = trained_model

    feature_importance["feature_selector_idx"] = feature_selector_idx
    feature_importance_set = pd.concat([feature_importance_set, feature_importance], ignore_index=True)

    forecast_dataset_df = pd.DataFrame({
        "feature_selector_idx": [feature_selector_idx] * len(forecast_dataset),
        "forecast_prob": forecast_dataset
    })
    forecast_dataset_set = pd.concat([forecast_dataset_set, forecast_dataset_df], ignore_index=True)
    
    train_dataset_proba["feature_selector_idx"] = feature_selector_idx
    train_dataset_proba_set = pd.concat([train_dataset_proba_set, train_dataset_proba], ignore_index=True)

    train_dataset_proba["feature_selector_idx"] = feature_selector_idx
    train_dataset_proba_set = pd.concat([train_dataset_proba_set, train_dataset_proba], ignore_index=True)

    best_threshold_df = pd.DataFrame({
    "feature_selector_idx": [feature_selector_idx],
    "best_threshold": [best_threshold]
    })
    best_threshold_set = pd.concat([best_threshold_set, best_threshold_df], ignore_index=True)

    roc_data["feature_selector_idx"] = feature_selector_idx
    roc_data_set = pd.concat([roc_data_set, roc_data], ignore_index=True)

    auc_score_df = pd.DataFrame({
    "feature_selector_idx": [feature_selector_idx],
    "auc_score": [auc_score]
    })
    auc_score_set = pd.concat([auc_score_set, auc_score_df], ignore_index=True)

    train_dataset_metrics["feature_selector_idx"] = feature_selector_idx
    train_dataset_metrics_set = pd.concat([train_dataset_metrics_set, train_dataset_metrics], ignore_index=True)

    metrics_dict = {
        "f1_score": metrics["f1_score"],
        "recall": metrics["recall"],
        "precision": metrics["precision"],
        "accuracy": metrics["accuracy"],
        "auc_score": metrics["auc_score"],
        "tp": metrics["dict_ftpn"]["tp"],
        "tn": metrics["dict_ftpn"]["tn"],
        "fp": metrics["dict_ftpn"]["fp"],
        "fn": metrics["dict_ftpn"]["fn"],
        "number_of_predictions": metrics["number_of_predictions"],
        "number_of_good_predictions": metrics["number_of_good_predictions"],
        "number_of_false_predictions": metrics["number_of_false_predictions"],
        "feature_selector_idx": feature_selector_idx  # 현재 필터 이름 추가
    }
    metrics_df = pd.DataFrame([metrics_dict])
    metrics_set = pd.concat([metrics_set, metrics_df], ignore_index=True)

    results["feature_selector_idx"] = feature_selector_idx
    results_set = pd.concat([results_set, results], ignore_index=True)

    dict_ftpn = metrics["dict_ftpn"]
    new_row = {
        'fn': dict_ftpn.get('fn'),
        'fp': dict_ftpn.get('fp'),
        'tn': dict_ftpn.get('tn'),
        'tp': dict_ftpn.get('tp'),
        'feature_selector_idx' : feature_selection_info["feature_selector_idx"],
        'feature_selector_name' : feature_selection_info["feature_selector_name"],
        'initial_feature_count' : feature_selection_info["initial_feature_count"],
        'final_feature_count' : feature_selection_info["final_feature_count"],
        'final_feature_selector_f2score' : feature_selection_info["Params"]["f2_score"],
        'final_feature_selector_best_k_percentile' : feature_selection_info["Params"]["best_k_percentile"]
    }
    
    opt_pl_fs_test_result_ftpn_df = pd.concat([opt_pl_fs_test_result_ftpn_df, pd.DataFrame([new_row])], ignore_index=True)
    features_values = feature_importance[["Features", "Importance"]].rename(columns={"Importance": "Importance(model)"+"_"+feature_selection_info["feature_selector_name"] })
    opt_pl_fs_test_result_features_values_dfs = pd.merge(
        opt_pl_fs_test_result_features_values_dfs,
        features_values,
        how='left',
        left_on='feature_name',
        right_on='Features'
    ).drop('Features', axis=1) # The .drop() method is used to drop the column

import pickle
import os

save_path = "data/result/select_feature"
os.makedirs(save_path, exist_ok=True)

dict_vars = [
    (trained_model_set, "trained_model_set")
]

df_vars = [
    (feature_importance_set, "feature_importance_set"),
    (forecast_dataset_set, "forecast_dataset_set"),
    (train_dataset_proba_set, "train_dataset_proba_set"),
    (best_threshold_set, "best_threshold_set"),
    (roc_data_set, "roc_data_set"),
    (auc_score_set, "auc_score_set"),
    (train_dataset_metrics_set, "train_dataset_metrics_set"),
    (metrics_set, "metrics_set"),
    (results_set, "results_set"),
    (opt_pl_fs_test_result_ftpn_df, "opt_pl_fs_test_result_ftpn_df"),
    (opt_pl_fs_test_result_features_values_dfs, "opt_pl_fs_test_result_features_values_dfs")
]

for var, name in dict_vars:
    file_path = os.path.join(save_path, f"{name}.pickle")
    with open(file_path, "wb") as f:
        pickle.dump(var, f)
    print(f"Saved {name} to {file_path}")

for var, name in df_vars:
    file_path = os.path.join(save_path, f"{name}.csv")
    var.to_csv(file_path, index=False)
    print(f"Saved {name} to {file_path}")

      Training the Random Forest model with cross-validation & hyperparameter tuning...

Fitting 3 folds for each of 18 candidates, totalling 54 fits

    Best parameters found: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 20}
    Best F2 (class=1) score (CV): 0.2192

     Forecasting the test dataset...
     Forecasting done!
Best threshold for F2 score: 0.6970 with F2 score: 0.6132
     Calculation of the ROC curve...
     Calculation done
     Scoring...
     Scoring done

     Creating the metrics...
      Training the Random Forest model with cross-validation & hyperparameter tuning...

Fitting 3 folds for each of 18 candidates, totalling 54 fits

    Best parameters found: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 20}
    Best F2 (class=1) score (CV): 0.1966

     Forecasting the test dataset...
     Forecasting done!
Best threshold for F2 score: 0.7980 with F2 score: 0.5182
     Calculation of the ROC curve...
     Calculation done
     Scoring...
     Scoring done

     Creating the metrics...
      Training the Random Forest model with cross-validation & hyperparameter tuning...

Fitting 3 folds for each of 18 candidates, totalling 54 fits

    Best parameters found: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 20}
    Best F2 (class=1) score (CV): 0.2145

     Forecasting the test dataset...
     Forecasting done!
Best threshold for F2 score: 0.7475 with F2 score: 0.6029
     Calculation of the ROC curve...
     Calculation done
     Scoring...
     Scoring done

     Creating the metrics...
      Training the Random Forest model with cross-validation & hyperparameter tuning...

Fitting 3 folds for each of 18 candidates, totalling 54 fits

    Best parameters found: {'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 20}
    Best F2 (class=1) score (CV): 0.2297

     Forecasting the test dataset...
     Forecasting done!
Best threshold for F2 score: 0.7980 with F2 score: 0.6238
     Calculation of the ROC curve...
     Calculation done
     Scoring...
     Scoring done

     Creating the metrics...
Saved trained_model_set to data/result/select_feature\trained_model_set.pickle
Saved feature_importance_set to data/result/select_feature\feature_importance_set.csv
Saved forecast_dataset_set to data/result/select_feature\forecast_dataset_set.csv
Saved train_dataset_proba_set to data/result/select_feature\train_dataset_proba_set.csv
Saved best_threshold_set to data/result/select_feature\best_threshold_set.csv
Saved roc_data_set to data/result/select_feature\roc_data_set.csv
Saved auc_score_set to data/result/select_feature\auc_score_set.csv
Saved train_dataset_metrics_set to data/result/select_feature\train_dataset_metrics_set.csv
Saved metrics_set to data/result/select_feature\metrics_set.csv
Saved results_set to data/result/select_feature\results_set.csv
Saved opt_pl_fs_test_result_ftpn_df to data/result/select_feature\opt_pl_fs_test_result_ftpn_df.csv
Saved opt_pl_fs_test_result_features_values_dfs to data/result/select_feature\opt_pl_fs_test_result_features_values_dfs.csv

In [ ]:
opt_pl_fs_test_result_ftpn_df

,fn,fp,tn,tp,feature_selector_idx,feature_selector_name,initial_feature_count,final_feature_count,final_feature_selector_f2score,final_feature_selector_best_k_percentile
0,6,178,709,12,0,FeatureFilter_variance,1650,1320,0.0,0.8
1,8,199,688,10,1,FeatureFilter_target_linear_correlation,1650,165,0.0,0.1
2,7,158,729,11,2,FeatureFilter_target_xicor_correlation,1650,1485,0.0,0.9
3,8,132,755,10,3,SFM_importances,1650,825,0.0,0.5

In [ ]:
opt_pl_fs_test_result_features_values_dfs

,feature_name,Importance(model)_FeatureFilter_variance,Importance(model)_FeatureFilter_target_linear_correlation,Importance(model)_FeatureFilter_target_xicor_correlation,Importance(model)_SFM_importances
0,X,0.000000,NaN,0.000000,0.000000
1,Y,0.008596,NaN,0.000000,NaN
2,Radius,0.004065,NaN,0.008714,0.006605
3,AC_COIL_FACTOR of 1103959_69_1133529_YPP,NaN,NaN,NaN,NaN
4,AC_COIL_FACTOR of 1103959_69_1133529_cp1_cp1p5,NaN,NaN,NaN,NaN
...,...,...,...,...,...
1646,FAILING_BINOUTS(1) of 1103959_69_JPP_GbPoPo,NaN,NaN,0.000000,NaN
1647,FAILING_BINOUTS(1) of 1103959_69_JPP_PoPo,NaN,NaN,0.000000,NaN
1648,FAILING_BINOUTS(1) of 1103959_69_JPP_SbPoPo,NaN,NaN,0.000000,NaN
1649,band gap dpat_ok for band gap,NaN,NaN,0.000000,NaN
1650,Pass/Fail,NaN,NaN,NaN,NaN

In [ ]:
train_dataset_proba_set

In [1]:
test_data

NameError: name 'test_data' is not defined

###### Model Parameter optimization with optuna

In [62]:
# feature select test : pipeline
## Apply the selected feature set feature_selection_info['final_features'] list to the modeling pipeline and return the modeling results

def pl_fs_test(
        train_data,
        feature_selection_info,
        train_parameters,
        test_data
        ):
    
    trained_model, feature_importance, train_parameters_info = train_model_rf_optuna(train_data.copy(), feature_selection_info, train_parameters)
    forecast_dataset, shap_values_random_forest = forecast(test_data, trained_model, feature_selection_info)
    train_dataset_proba, best_threshold = find_best_threshold(trained_model, train_data.copy(), feature_selection_info)
    roc_data, auc_score = roc_from_scratch(forecast_dataset, test_data, partitions=100)
    train_dataset_metrics = create_metrics_on_train(train_dataset_proba, best_threshold)
    metrics = create_metrics(forecast_dataset, test_data, auc_score, best_threshold)
    results = create_results(forecast_dataset, test_data, best_threshold)
    
    return \
        trained_model, \
        feature_importance, \
        forecast_dataset, \
        train_dataset_proba, \
        best_threshold, \
        roc_data, \
        auc_score, \
        train_dataset_metrics, \
        metrics, \
        results

In [63]:
# Optimal feature set performance check
# feature select test - submit and summary result

opt_pl_fs_test_result_ftpn_df_rf_optuna = pd.DataFrame()
opt_pl_fs_test_result_features_values_dfs_rf_optuna = pd.DataFrame(
    list(train_data.columns), 
    columns=['feature_name']
)

feature_importance_set = pd.DataFrame()

for fileter_name, feature_selection_info in feature_selection_results.items():
    trained_model, \
    feature_importance, \
    forecast_dataset, \
    train_dataset_proba, \
    best_threshold, \
    roc_data, \
    auc_score, \
    train_dataset_metrics, \
    metrics, \
    results \
    = \
    pl_fs_test(
            train_data,
            feature_selection_info,
            train_parameters_list_default["rf_optuna"],
            test_data
            )

    dict_ftpn = metrics["dict_ftpn"]
    
    new_row = {
        'fn': dict_ftpn.get('fn'),
        'fp': dict_ftpn.get('fp'),
        'tn': dict_ftpn.get('tn'),
        'tp': dict_ftpn.get('tp'),
        'feature_selector_idx' : feature_selection_info["feature_selector_idx"],
        'feature_selector_name' : feature_selection_info["feature_selector_name"],
        'initial_feature_count' : feature_selection_info["initial_feature_count"],
        'final_feature_count' : feature_selection_info["final_feature_count"],
        'final_feature_selector_f2score' : feature_selection_info["Params"]["f2_score"],
        'final_feature_selector_best_k_percentile' : feature_selection_info["Params"]["best_k_percentile"]
    }
    
    opt_pl_fs_test_result_ftpn_df_rf_optuna = pd.concat([opt_pl_fs_test_result_ftpn_df_rf_optuna, pd.DataFrame([new_row])], ignore_index=True)
    features_values = feature_importance[["Features", "Importance"]].rename(columns={"Importance": "Importance(model)"+"_"+feature_selection_info["feature_selector_name"] })

    opt_pl_fs_test_result_features_values_dfs_rf_optuna = pd.merge(
        opt_pl_fs_test_result_features_values_dfs_rf_optuna,
        features_values,
        how='left',
        left_on='feature_name',
        right_on='Features'
    ).drop('Features', axis=1) # The .drop() method is used to drop the column

[I 2025-09-02 09:55:25,812] A new study created in memory with name: no-name-cfa92ab1-9980-41ae-ab01-c0d9c9721fbb

     Training the Random Forest model with Optuna hyperparameter tuning...

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2025-09-02 09:55:35,494] Trial 0 finished with value: 0.15363062594816232 and parameters: {'n_estimators': 219, 'max_depth': 20, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 1289}. Best is trial 0 with value: 0.15363062594816232.
[I 2025-09-02 09:56:10,851] Trial 1 finished with value: 0.18363941025912284 and parameters: {'n_estimators': 239, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 0.5, 'class_weight_multiplier': 1417}. Best is trial 1 with value: 0.18363941025912284.
[I 2025-09-02 09:56:18,075] Trial 2 finished with value: 0.04502888415931894 and parameters: {'n_estimators': 242, 'max_depth': 29, 'min_samples_split': 19, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 544}. Best is trial 1 with value: 0.18363941025912284.
[I 2025-09-02 09:56:37,231] Trial 3 finished with value: 0.19208381401085584 and parameters: {'n_estimators': 132, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight_multiplier': 821}. Best is trial 3 with value: 0.19208381401085584.
[I 2025-09-02 09:56:40,601] Trial 4 finished with value: 0.23991698498277442 and parameters: {'n_estimators': 259, 'max_depth': 12, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 1520}. Best is trial 4 with value: 0.23991698498277442.
[I 2025-09-02 09:57:47,917] Trial 5 finished with value: 0.015384615384615385 and parameters: {'n_estimators': 282, 'max_depth': 28, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight_multiplier': 3276}. Best is trial 4 with value: 0.23991698498277442.
[I 2025-09-02 09:57:50,502] Trial 6 finished with value: 0.05890635186409834 and parameters: {'n_estimators': 118, 'max_depth': 26, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'class_weight_multiplier': 2161}. Best is trial 4 with value: 0.23991698498277442.
[I 2025-09-02 09:58:37,793] Trial 7 finished with value: 0.11475450114002672 and parameters: {'n_estimators': 235, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 0.5, 'class_weight_multiplier': 1631}. Best is trial 4 with value: 0.23991698498277442.
[I 2025-09-02 09:59:40,052] Trial 8 finished with value: 0.10506016621491876 and parameters: {'n_estimators': 191, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.8, 'class_weight_multiplier': 915}. Best is trial 4 with value: 0.23991698498277442.
[I 2025-09-02 09:59:45,318] Trial 9 finished with value: 0.04332611832611833 and parameters: {'n_estimators': 253, 'max_depth': 26, 'min_samples_split': 19, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 2732}. Best is trial 4 with value: 0.23991698498277442.
[I 2025-09-02 10:01:16,902] Trial 10 finished with value: 0.044610507246376815 and parameters: {'n_estimators': 299, 'max_depth': 14, 'min_samples_split': 14, 'min_samples_leaf': 4, 'max_features': 0.8, 'class_weight_multiplier': 49}. Best is trial 4 with value: 0.23991698498277442.
[I 2025-09-02 10:01:46,631] Trial 11 finished with value: 0.19843776579457692 and parameters: {'n_estimators': 162, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight_multiplier': 2228}. Best is trial 4 with value: 0.23991698498277442.
[I 2025-09-02 10:01:49,634] Trial 12 finished with value: 0.24239749363383734 and parameters: {'n_estimators': 168, 'max_depth': 12, 'min_samples_split': 14, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 2265}. Best is trial 12 with value: 0.24239749363383734.
[I 2025-09-02 10:01:52,847] Trial 13 finished with value: 0.22608422187330962 and parameters: {'n_estimators': 179, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 2135}. Best is trial 12 with value: 0.24239749363383734.
[I 2025-09-02 10:01:56,574] Trial 14 finished with value: 0.160829704777043 and parameters: {'n_estimators': 158, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 2839}. Best is trial 12 with value: 0.24239749363383734.
[I 2025-09-02 10:02:01,098] Trial 15 finished with value: 0.1469461225407919 and parameters: {'n_estimators': 209, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'class_weight_multiplier': 2704}. Best is trial 12 with value: 0.24239749363383734.
[I 2025-09-02 10:02:06,351] Trial 16 finished with value: 0.20783323777083434 and parameters: {'n_estimators': 268, 'max_depth': 14, 'min_samples_split': 17, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 1964}. Best is trial 12 with value: 0.24239749363383734.
[I 2025-09-02 10:03:16,758] Trial 17 finished with value: 0.030303030303030304 and parameters: {'n_estimators': 157, 'max_depth': 23, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 0.8, 'class_weight_multiplier': 3522}. Best is trial 12 with value: 0.24239749363383734.
[I 2025-09-02 10:03:18,946] Trial 18 finished with value: 0.13615155055120892 and parameters: {'n_estimators': 102, 'max_depth': 17, 'min_samples_split': 17, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 1659}. Best is trial 12 with value: 0.24239749363383734.
[I 2025-09-02 10:03:22,340] Trial 19 finished with value: 0.233332494182741 and parameters: {'n_estimators': 190, 'max_depth': 13, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 2486}. Best is trial 12 with value: 0.24239749363383734.
[I 2025-09-02 10:04:53,499] Trial 20 finished with value: 0.015151515151515152 and parameters: {'n_estimators': 220, 'max_depth': 23, 'min_samples_split': 17, 'min_samples_leaf': 4, 'max_features': 0.8, 'class_weight_multiplier': 1161}. Best is trial 12 with value: 0.24239749363383734.
[I 2025-09-02 10:04:56,849] Trial 21 finished with value: 0.255218465596734 and parameters: {'n_estimators': 189, 'max_depth': 12, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 2497}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:05:00,102] Trial 22 finished with value: 0.24240897249270618 and parameters: {'n_estimators': 172, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 1860}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:05:02,720] Trial 23 finished with value: 0.17941609283976714 and parameters: {'n_estimators': 137, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 2472}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:05:05,578] Trial 24 finished with value: 0.24323788516355024 and parameters: {'n_estimators': 173, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 1878}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:05:07,965] Trial 25 finished with value: 0.25336747196125214 and parameters: {'n_estimators': 143, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 1777}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:05:10,321] Trial 26 finished with value: 0.24755488112713842 and parameters: {'n_estimators': 144, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 3053}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:05:12,622] Trial 27 finished with value: 0.2541587675460993 and parameters: {'n_estimators': 140, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 2987}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:05:54,662] Trial 28 finished with value: 0.13744053766814351 and parameters: {'n_estimators': 120, 'max_depth': 15, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_features': 0.8, 'class_weight_multiplier': 3133}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:05:57,743] Trial 29 finished with value: 0.1419624143487368 and parameters: {'n_estimators': 150, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 2506}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:06:00,089] Trial 30 finished with value: 0.1287703657954325 and parameters: {'n_estimators': 107, 'max_depth': 21, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 3518}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:06:02,626] Trial 31 finished with value: 0.2543808362224433 and parameters: {'n_estimators': 146, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 3071}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:06:04,813] Trial 32 finished with value: 0.2496342473189114 and parameters: {'n_estimators': 126, 'max_depth': 11, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 2954}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:06:07,380] Trial 33 finished with value: 0.2536358562876075 and parameters: {'n_estimators': 142, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 3215}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:06:10,571] Trial 34 finished with value: 0.23119507341663717 and parameters: {'n_estimators': 187, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 3424}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:06:51,204] Trial 35 finished with value: 0.210663443272612 and parameters: {'n_estimators': 203, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight_multiplier': 3214}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:06:53,943] Trial 36 finished with value: 0.24848828608019785 and parameters: {'n_estimators': 130, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 3288}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:06:55,711] Trial 37 finished with value: 0.2526690146522956 and parameters: {'n_estimators': 113, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 2847}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:07:28,665] Trial 38 finished with value: 0.1410072636477131 and parameters: {'n_estimators': 150, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 0.5, 'class_weight_multiplier': 2634}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:07:30,956] Trial 39 finished with value: 0.24551494616662284 and parameters: {'n_estimators': 135, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 2988}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:07:34,864] Trial 40 finished with value: 0.23917225078723056 and parameters: {'n_estimators': 223, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight_multiplier': 3234}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:07:37,338] Trial 41 finished with value: 0.2526370679820831 and parameters: {'n_estimators': 141, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 3355}. Best is trial 21 with value: 0.255218465596734.
[I 2025-09-02 10:07:39,758] Trial 42 finished with value: 0.25900891627616596 and parameters: {'n_estimators': 151, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 1421}. Best is trial 42 with value: 0.25900891627616596.
[I 2025-09-02 10:07:42,700] Trial 43 finished with value: 0.060220702804658036 and parameters: {'n_estimators': 123, 'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 1357}. Best is trial 42 with value: 0.25900891627616596.
[I 2025-09-02 10:07:45,697] Trial 44 finished with value: 0.24683171132955467 and parameters: {'n_estimators': 180, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 1217}. Best is trial 42 with value: 0.25900891627616596.
[I 2025-09-02 10:08:20,290] Trial 45 finished with value: 0.15384145397799817 and parameters: {'n_estimators': 163, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight_multiplier': 930}. Best is trial 42 with value: 0.25900891627616596.
[I 2025-09-02 10:08:22,639] Trial 46 finished with value: 0.24892800717253682 and parameters: {'n_estimators': 149, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 242}. Best is trial 42 with value: 0.25900891627616596.
[I 2025-09-02 10:09:26,454] Trial 47 finished with value: 0.1560469715595026 and parameters: {'n_estimators': 197, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 4, 'max_features': 0.8, 'class_weight_multiplier': 2914}. Best is trial 42 with value: 0.25900891627616596.
[I 2025-09-02 10:09:29,533] Trial 48 finished with value: 0.17412735664417045 and parameters: {'n_estimators': 155, 'max_depth': 15, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 2323}. Best is trial 42 with value: 0.25900891627616596.
[I 2025-09-02 10:09:32,575] Trial 49 finished with value: 0.24320334867233656 and parameters: {'n_estimators': 165, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 2659}. Best is trial 42 with value: 0.25900891627616596.

      Best parameters found (Optuna): {'n_estimators': 151, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 1421}
      Best F2 (class=1) score (CV): 0.2590

     Forecasting the test dataset...
     Forecasting done!
Best threshold for F2 score: 0.6364 with F2 score: 0.7164
     Calculation of the ROC curve...
     Calculation done
     Scoring...
     Scoring done

[I 2025-09-02 10:09:34,631] A new study created in memory with name: no-name-a3178f80-a54c-4e28-becb-8bc3dacbc863

     Creating the metrics...
     Training the Random Forest model with Optuna hyperparameter tuning...

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2025-09-02 10:09:36,524] Trial 0 finished with value: 0.21191784400756708 and parameters: {'n_estimators': 215, 'max_depth': 17, 'min_samples_split': 20, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight_multiplier': 292}. Best is trial 0 with value: 0.21191784400756708.
[I 2025-09-02 10:09:46,160] Trial 1 finished with value: 0.1949030335912329 and parameters: {'n_estimators': 208, 'max_depth': 11, 'min_samples_split': 17, 'min_samples_leaf': 3, 'max_features': 0.8, 'class_weight_multiplier': 352}. Best is trial 0 with value: 0.21191784400756708.
[I 2025-09-02 10:09:56,240] Trial 2 finished with value: 0.1866866574273654 and parameters: {'n_estimators': 205, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.8, 'class_weight_multiplier': 1917}. Best is trial 0 with value: 0.21191784400756708.
[I 2025-09-02 10:09:57,832] Trial 3 finished with value: 0.18930019947884996 and parameters: {'n_estimators': 174, 'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight_multiplier': 2946}. Best is trial 0 with value: 0.21191784400756708.
[I 2025-09-02 10:10:04,388] Trial 4 finished with value: 0.19017856404018335 and parameters: {'n_estimators': 188, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight_multiplier': 637}. Best is trial 0 with value: 0.21191784400756708.
[I 2025-09-02 10:10:06,484] Trial 5 finished with value: 0.19286726647891314 and parameters: {'n_estimators': 243, 'max_depth': 17, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 2075}. Best is trial 0 with value: 0.21191784400756708.
[I 2025-09-02 10:10:09,105] Trial 6 finished with value: 0.18704736587358634 and parameters: {'n_estimators': 290, 'max_depth': 21, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'class_weight_multiplier': 1214}. Best is trial 0 with value: 0.21191784400756708.
[I 2025-09-02 10:10:10,359] Trial 7 finished with value: 0.1871473277897438 and parameters: {'n_estimators': 152, 'max_depth': 14, 'min_samples_split': 19, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 2098}. Best is trial 0 with value: 0.21191784400756708.
[I 2025-09-02 10:10:12,451] Trial 8 finished with value: 0.19700292214898574 and parameters: {'n_estimators': 253, 'max_depth': 15, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'class_weight_multiplier': 2938}. Best is trial 0 with value: 0.21191784400756708.
[I 2025-09-02 10:10:24,491] Trial 9 finished with value: 0.19245563661065876 and parameters: {'n_estimators': 240, 'max_depth': 13, 'min_samples_split': 11, 'min_samples_leaf': 8, 'max_features': 0.8, 'class_weight_multiplier': 1739}. Best is trial 0 with value: 0.21191784400756708.
[I 2025-09-02 10:10:29,143] Trial 10 finished with value: 0.11947584266970368 and parameters: {'n_estimators': 104, 'max_depth': 27, 'min_samples_split': 20, 'min_samples_leaf': 10, 'max_features': 0.5, 'class_weight_multiplier': 922}. Best is trial 0 with value: 0.21191784400756708.
[I 2025-09-02 10:10:31,715] Trial 11 finished with value: 0.22577895385357755 and parameters: {'n_estimators': 277, 'max_depth': 22, 'min_samples_split': 14, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 3425}. Best is trial 11 with value: 0.22577895385357755.
[I 2025-09-02 10:10:34,415] Trial 12 finished with value: 0.20295328188532075 and parameters: {'n_estimators': 289, 'max_depth': 23, 'min_samples_split': 15, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 3538}. Best is trial 11 with value: 0.22577895385357755.
[I 2025-09-02 10:10:36,299] Trial 13 finished with value: 0.07513552684755494 and parameters: {'n_estimators': 265, 'max_depth': 24, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 128}. Best is trial 11 with value: 0.22577895385357755.
[I 2025-09-02 10:10:38,561] Trial 14 finished with value: 0.15607244916562862 and parameters: {'n_estimators': 222, 'max_depth': 30, 'min_samples_split': 18, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'class_weight_multiplier': 1351}. Best is trial 11 with value: 0.22577895385357755.
[I 2025-09-02 10:10:44,372] Trial 15 finished with value: 0.1785676377265382 and parameters: {'n_estimators': 149, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight_multiplier': 2545}. Best is trial 11 with value: 0.22577895385357755.
[I 2025-09-02 10:10:46,850] Trial 16 finished with value: 0.21983425228436643 and parameters: {'n_estimators': 271, 'max_depth': 21, 'min_samples_split': 14, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 3541}. Best is trial 11 with value: 0.22577895385357755.
[I 2025-09-02 10:10:49,253] Trial 17 finished with value: 0.21951819665857628 and parameters: {'n_estimators': 273, 'max_depth': 21, 'min_samples_split': 13, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 3507}. Best is trial 11 with value: 0.22577895385357755.
[I 2025-09-02 10:11:01,530] Trial 18 finished with value: 0.12473571646900786 and parameters: {'n_estimators': 296, 'max_depth': 25, 'min_samples_split': 8, 'min_samples_leaf': 10, 'max_features': 0.5, 'class_weight_multiplier': 3062}. Best is trial 11 with value: 0.22577895385357755.
[I 2025-09-02 10:11:20,041] Trial 19 finished with value: 0.14621933384255054 and parameters: {'n_estimators': 271, 'max_depth': 27, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 0.8, 'class_weight_multiplier': 2412}. Best is trial 11 with value: 0.22577895385357755.
[I 2025-09-02 10:11:22,149] Trial 20 finished with value: 0.20302990611838506 and parameters: {'n_estimators': 232, 'max_depth': 20, 'min_samples_split': 14, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 3250}. Best is trial 11 with value: 0.22577895385357755.
[I 2025-09-02 10:11:24,601] Trial 21 finished with value: 0.2043578957196373 and parameters: {'n_estimators': 270, 'max_depth': 22, 'min_samples_split': 13, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 3463}. Best is trial 11 with value: 0.22577895385357755.
[I 2025-09-02 10:11:27,012] Trial 22 finished with value: 0.22948082075315296 and parameters: {'n_estimators': 275, 'max_depth': 20, 'min_samples_split': 16, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 3247}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:11:29,265] Trial 23 finished with value: 0.20817640996735384 and parameters: {'n_estimators': 256, 'max_depth': 19, 'min_samples_split': 17, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 2558}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:11:31,813] Trial 24 finished with value: 0.13139797248364005 and parameters: {'n_estimators': 282, 'max_depth': 26, 'min_samples_split': 15, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 3139}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:11:34,245] Trial 25 finished with value: 0.20259981109037714 and parameters: {'n_estimators': 256, 'max_depth': 23, 'min_samples_split': 16, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 2706}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:11:36,845] Trial 26 finished with value: 0.20830418342598037 and parameters: {'n_estimators': 300, 'max_depth': 20, 'min_samples_split': 18, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'class_weight_multiplier': 3206}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:11:38,778] Trial 27 finished with value: 0.2053382026676646 and parameters: {'n_estimators': 236, 'max_depth': 16, 'min_samples_split': 13, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 2785}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:11:56,415] Trial 28 finished with value: 0.174519206523012 and parameters: {'n_estimators': 276, 'max_depth': 22, 'min_samples_split': 15, 'min_samples_leaf': 9, 'max_features': 0.8, 'class_weight_multiplier': 3339}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:06,948] Trial 29 finished with value: 0.1354579048862396 and parameters: {'n_estimators': 220, 'max_depth': 29, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 0.5, 'class_weight_multiplier': 2237}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:09,238] Trial 30 finished with value: 0.18612039369009625 and parameters: {'n_estimators': 258, 'max_depth': 19, 'min_samples_split': 12, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'class_weight_multiplier': 2820}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:11,847] Trial 31 finished with value: 0.22052046079896157 and parameters: {'n_estimators': 279, 'max_depth': 21, 'min_samples_split': 13, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 3530}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:14,539] Trial 32 finished with value: 0.18923046602185883 and parameters: {'n_estimators': 283, 'max_depth': 24, 'min_samples_split': 16, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 3299}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:16,797] Trial 33 finished with value: 0.20840462765695475 and parameters: {'n_estimators': 248, 'max_depth': 21, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 3134}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:19,519] Trial 34 finished with value: 0.19583456529364376 and parameters: {'n_estimators': 298, 'max_depth': 19, 'min_samples_split': 17, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 3531}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:30,728] Trial 35 finished with value: 0.18095570942102385 and parameters: {'n_estimators': 194, 'max_depth': 17, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': 0.8, 'class_weight_multiplier': 2984}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:33,127] Trial 36 finished with value: 0.1863432066018273 and parameters: {'n_estimators': 266, 'max_depth': 22, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'class_weight_multiplier': 3378}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:34,632] Trial 37 finished with value: 0.1940737097047836 and parameters: {'n_estimators': 210, 'max_depth': 10, 'min_samples_split': 18, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 3268}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:36,918] Trial 38 finished with value: 0.20938723632096595 and parameters: {'n_estimators': 231, 'max_depth': 24, 'min_samples_split': 15, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'class_weight_multiplier': 2941}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:47,183] Trial 39 finished with value: 0.18326149326731697 and parameters: {'n_estimators': 172, 'max_depth': 18, 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_features': 0.8, 'class_weight_multiplier': 1678}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:49,600] Trial 40 finished with value: 0.18184941789129225 and parameters: {'n_estimators': 282, 'max_depth': 21, 'min_samples_split': 4, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 538}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:52,122] Trial 41 finished with value: 0.22182548943207334 and parameters: {'n_estimators': 278, 'max_depth': 21, 'min_samples_split': 14, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 3542}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:54,713] Trial 42 finished with value: 0.20850365015848427 and parameters: {'n_estimators': 289, 'max_depth': 20, 'min_samples_split': 14, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 3368}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:57,141] Trial 43 finished with value: 0.17625392585760372 and parameters: {'n_estimators': 263, 'max_depth': 23, 'min_samples_split': 16, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 3535}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:12:59,854] Trial 44 finished with value: 0.17721135967499793 and parameters: {'n_estimators': 278, 'max_depth': 22, 'min_samples_split': 13, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 3199}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:13:09,201] Trial 45 finished with value: 0.18420201015015256 and parameters: {'n_estimators': 249, 'max_depth': 17, 'min_samples_split': 11, 'min_samples_leaf': 7, 'max_features': 0.5, 'class_weight_multiplier': 3063}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:13:11,781] Trial 46 finished with value: 0.18954601462653403 and parameters: {'n_estimators': 291, 'max_depth': 20, 'min_samples_split': 19, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'class_weight_multiplier': 2925}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:13:14,169] Trial 47 finished with value: 0.20846089495170372 and parameters: {'n_estimators': 244, 'max_depth': 25, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'class_weight_multiplier': 3368}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:13:15,128] Trial 48 finished with value: 0.19908603167424888 and parameters: {'n_estimators': 100, 'max_depth': 19, 'min_samples_split': 17, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 1466}. Best is trial 22 with value: 0.22948082075315296.
[I 2025-09-02 10:13:20,242] Trial 49 finished with value: 0.19491931334860788 and parameters: {'n_estimators': 124, 'max_depth': 21, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 0.5, 'class_weight_multiplier': 1031}. Best is trial 22 with value: 0.22948082075315296.

      Best parameters found (Optuna): {'n_estimators': 275, 'max_depth': 20, 'min_samples_split': 16, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 3247}
      Best F2 (class=1) score (CV): 0.2295

     Forecasting the test dataset...
     Forecasting done!
Best threshold for F2 score: 0.5960 with F2 score: 0.7649
     Calculation of the ROC curve...
     Calculation done
     Scoring...
     Scoring done

[I 2025-09-02 10:13:25,856] A new study created in memory with name: no-name-87969bab-643e-424c-82fa-f390b9cab578

     Creating the metrics...
     Training the Random Forest model with Optuna hyperparameter tuning...

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2025-09-02 10:13:28,836] Trial 0 finished with value: 0.2095985749815151 and parameters: {'n_estimators': 181, 'max_depth': 14, 'min_samples_split': 17, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'class_weight_multiplier': 3489}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:13:33,209] Trial 1 finished with value: 0.16241313737643645 and parameters: {'n_estimators': 279, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 2048}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:14:05,138] Trial 2 finished with value: 0.0402864044168392 and parameters: {'n_estimators': 142, 'max_depth': 28, 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_features': 0.5, 'class_weight_multiplier': 256}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:15:16,952] Trial 3 finished with value: 0.014925373134328356 and parameters: {'n_estimators': 185, 'max_depth': 29, 'min_samples_split': 11, 'min_samples_leaf': 2, 'max_features': 0.8, 'class_weight_multiplier': 3531}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:16:27,962] Trial 4 finished with value: 0.030076888285843505 and parameters: {'n_estimators': 294, 'max_depth': 26, 'min_samples_split': 17, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight_multiplier': 405}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:17:29,148] Trial 5 finished with value: 0.030076888285843505 and parameters: {'n_estimators': 252, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 0.5, 'class_weight_multiplier': 894}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:17:32,505] Trial 6 finished with value: 0.2095985749815151 and parameters: {'n_estimators': 181, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 3165}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:17:37,885] Trial 7 finished with value: 0.13687007486495967 and parameters: {'n_estimators': 276, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 815}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:18:24,732] Trial 8 finished with value: 0.031009615384615385 and parameters: {'n_estimators': 207, 'max_depth': 21, 'min_samples_split': 13, 'min_samples_leaf': 7, 'max_features': 0.5, 'class_weight_multiplier': 80}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:18:27,761] Trial 9 finished with value: 0.10275739745662318 and parameters: {'n_estimators': 151, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 754}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:18:58,447] Trial 10 finished with value: 0.1966601045286936 and parameters: {'n_estimators': 108, 'max_depth': 10, 'min_samples_split': 20, 'min_samples_leaf': 5, 'max_features': 0.8, 'class_weight_multiplier': 2468}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:19:01,875] Trial 11 finished with value: 0.19891481429775443 and parameters: {'n_estimators': 197, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'class_weight_multiplier': 3462}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:19:05,775] Trial 12 finished with value: 0.16251791980158928 and parameters: {'n_estimators': 228, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'class_weight_multiplier': 2874}. Best is trial 0 with value: 0.2095985749815151.
[I 2025-09-02 10:19:08,256] Trial 13 finished with value: 0.26037351307741374 and parameters: {'n_estimators': 164, 'max_depth': 11, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 2887}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:19:10,552] Trial 14 finished with value: 0.2535199258225914 and parameters: {'n_estimators': 144, 'max_depth': 12, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 2713}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:19:12,878] Trial 15 finished with value: 0.25091686854067563 and parameters: {'n_estimators': 142, 'max_depth': 10, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 1732}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:19:46,340] Trial 16 finished with value: 0.062429922182244156 and parameters: {'n_estimators': 102, 'max_depth': 17, 'min_samples_split': 18, 'min_samples_leaf': 1, 'max_features': 0.8, 'class_weight_multiplier': 2549}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:19:48,881] Trial 17 finished with value: 0.2581080921371077 and parameters: {'n_estimators': 161, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 1616}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:19:51,661] Trial 18 finished with value: 0.13843175263667262 and parameters: {'n_estimators': 162, 'max_depth': 18, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 1454}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:20:27,464] Trial 19 finished with value: 0.1653953180325841 and parameters: {'n_estimators': 125, 'max_depth': 12, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_features': 0.8, 'class_weight_multiplier': 2124}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:20:31,436] Trial 20 finished with value: 0.12930202217873452 and parameters: {'n_estimators': 225, 'max_depth': 22, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 1346}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:20:33,921] Trial 21 finished with value: 0.25273920303277736 and parameters: {'n_estimators': 163, 'max_depth': 12, 'min_samples_split': 18, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 2707}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:20:35,760] Trial 22 finished with value: 0.24605143779134062 and parameters: {'n_estimators': 117, 'max_depth': 12, 'min_samples_split': 20, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight_multiplier': 2174}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:20:37,806] Trial 23 finished with value: 0.24479911912613805 and parameters: {'n_estimators': 127, 'max_depth': 10, 'min_samples_split': 16, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 2998}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:20:40,479] Trial 24 finished with value: 0.25374978598160597 and parameters: {'n_estimators': 161, 'max_depth': 12, 'min_samples_split': 19, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'class_weight_multiplier': 1577}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:20:43,262] Trial 25 finished with value: 0.16088265121371972 and parameters: {'n_estimators': 165, 'max_depth': 16, 'min_samples_split': 18, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight_multiplier': 1374}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:20:46,212] Trial 26 finished with value: 0.255421522217658 and parameters: {'n_estimators': 210, 'max_depth': 11, 'min_samples_split': 18, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 1653}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:20:49,391] Trial 27 finished with value: 0.2578459628345212 and parameters: {'n_estimators': 219, 'max_depth': 10, 'min_samples_split': 16, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 1872}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:21:48,564] Trial 28 finished with value: 0.015151515151515152 and parameters: {'n_estimators': 235, 'max_depth': 25, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight_multiplier': 1222}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:22:47,145] Trial 29 finished with value: 0.13663319845153452 and parameters: {'n_estimators': 183, 'max_depth': 14, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': 0.8, 'class_weight_multiplier': 1967}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:22:51,106] Trial 30 finished with value: 0.23547867126627336 and parameters: {'n_estimators': 244, 'max_depth': 13, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 2379}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:22:54,285] Trial 31 finished with value: 0.25212219270084707 and parameters: {'n_estimators': 218, 'max_depth': 10, 'min_samples_split': 17, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 1096}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:22:57,362] Trial 32 finished with value: 0.2600031410746217 and parameters: {'n_estimators': 203, 'max_depth': 11, 'min_samples_split': 16, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 1803}. Best is trial 13 with value: 0.26037351307741374.
[I 2025-09-02 10:23:00,322] Trial 33 finished with value: 0.2651224570322347 and parameters: {'n_estimators': 195, 'max_depth': 11, 'min_samples_split': 16, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 1953}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:23:03,872] Trial 34 finished with value: 0.14486463835801078 and parameters: {'n_estimators': 191, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight_multiplier': 2279}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:23:06,724] Trial 35 finished with value: 0.21950226949727814 and parameters: {'n_estimators': 179, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'class_weight_multiplier': 1905}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:23:54,586] Trial 36 finished with value: 0.015151515151515152 and parameters: {'n_estimators': 173, 'max_depth': 30, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight_multiplier': 1718}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:23:58,014] Trial 37 finished with value: 0.2582240352934896 and parameters: {'n_estimators': 197, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight_multiplier': 3300}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:24:01,702] Trial 38 finished with value: 0.2351698974110028 and parameters: {'n_estimators': 197, 'max_depth': 13, 'min_samples_split': 17, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight_multiplier': 3196}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:25:09,485] Trial 39 finished with value: 0.14230787967360858 and parameters: {'n_estimators': 206, 'max_depth': 15, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': 0.8, 'class_weight_multiplier': 3292}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:25:56,866] Trial 40 finished with value: 0.17537411135009112 and parameters: {'n_estimators': 265, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 0.5, 'class_weight_multiplier': 3373}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:25:59,461] Trial 41 finished with value: 0.2523199099066775 and parameters: {'n_estimators': 172, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 3044}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:26:02,249] Trial 42 finished with value: 0.25387849584278155 and parameters: {'n_estimators': 190, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight_multiplier': 1125}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:26:04,758] Trial 43 finished with value: 0.24154582996670215 and parameters: {'n_estimators': 155, 'max_depth': 13, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 3532}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:26:08,211] Trial 44 finished with value: 0.1681769490359714 and parameters: {'n_estimators': 201, 'max_depth': 15, 'min_samples_split': 17, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight_multiplier': 510}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:26:10,783] Trial 45 finished with value: 0.25265643169772034 and parameters: {'n_estimators': 174, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 2862}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:26:15,441] Trial 46 finished with value: 0.21749879696899566 and parameters: {'n_estimators': 299, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 1556}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:26:51,670] Trial 47 finished with value: 0.029857397504456328 and parameters: {'n_estimators': 150, 'max_depth': 24, 'min_samples_split': 14, 'min_samples_leaf': 5, 'max_features': 0.5, 'class_weight_multiplier': 2532}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:26:54,344] Trial 48 finished with value: 0.14284119903464892 and parameters: {'n_estimators': 134, 'max_depth': 20, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'class_weight_multiplier': 2040}. Best is trial 33 with value: 0.2651224570322347.
[I 2025-09-02 10:26:57,590] Trial 49 finished with value: 0.23676823435319205 and parameters: {'n_estimators': 190, 'max_depth': 13, 'min_samples_split': 19, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 2313}. Best is trial 33 with value: 0.2651224570322347.

      Best parameters found (Optuna): {'n_estimators': 195, 'max_depth': 11, 'min_samples_split': 16, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 1953}
      Best F2 (class=1) score (CV): 0.2651

     Forecasting the test dataset...
     Forecasting done!
Best threshold for F2 score: 0.6364 with F2 score: 0.7216
     Calculation of the ROC curve...
     Calculation done
     Scoring...
     Scoring done

[I 2025-09-02 10:27:00,672] A new study created in memory with name: no-name-3f313189-92b1-4b4b-8d08-2c03a568d81f

     Creating the metrics...
     Training the Random Forest model with Optuna hyperparameter tuning...

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2025-09-02 10:28:08,313] Trial 0 finished with value: 0.17844455563947612 and parameters: {'n_estimators': 296, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 0.8, 'class_weight_multiplier': 1286}. Best is trial 0 with value: 0.17844455563947612.
[I 2025-09-02 10:29:14,162] Trial 1 finished with value: 0.06702802581319896 and parameters: {'n_estimators': 241, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 0.8, 'class_weight_multiplier': 2368}. Best is trial 0 with value: 0.17844455563947612.
[I 2025-09-02 10:30:07,975] Trial 2 finished with value: 0.17013194698927075 and parameters: {'n_estimators': 240, 'max_depth': 12, 'min_samples_split': 18, 'min_samples_leaf': 10, 'max_features': 0.8, 'class_weight_multiplier': 3104}. Best is trial 0 with value: 0.17844455563947612.
[I 2025-09-02 10:31:06,590] Trial 3 finished with value: 0.06695959942954102 and parameters: {'n_estimators': 300, 'max_depth': 22, 'min_samples_split': 13, 'min_samples_leaf': 8, 'max_features': 0.5, 'class_weight_multiplier': 629}. Best is trial 0 with value: 0.17844455563947612.
[I 2025-09-02 10:31:46,717] Trial 4 finished with value: 0.17664834134113166 and parameters: {'n_estimators': 254, 'max_depth': 12, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight_multiplier': 1692}. Best is trial 0 with value: 0.17844455563947612.
[I 2025-09-02 10:31:49,766] Trial 5 finished with value: 0.1387923057998657 and parameters: {'n_estimators': 157, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 2815}. Best is trial 0 with value: 0.17844455563947612.
[I 2025-09-02 10:32:49,162] Trial 6 finished with value: 0.13249909432258122 and parameters: {'n_estimators': 246, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': 0.8, 'class_weight_multiplier': 2638}. Best is trial 0 with value: 0.17844455563947612.
[I 2025-09-02 10:34:05,367] Trial 7 finished with value: 0.014925373134328356 and parameters: {'n_estimators': 270, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 0.8, 'class_weight_multiplier': 190}. Best is trial 0 with value: 0.17844455563947612.
[I 2025-09-02 10:34:37,117] Trial 8 finished with value: 0.17020620001481496 and parameters: {'n_estimators': 222, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.5, 'class_weight_multiplier': 297}. Best is trial 0 with value: 0.17844455563947612.
[I 2025-09-02 10:35:56,604] Trial 9 finished with value: 0.015151515151515152 and parameters: {'n_estimators': 273, 'max_depth': 26, 'min_samples_split': 17, 'min_samples_leaf': 2, 'max_features': 0.8, 'class_weight_multiplier': 2708}. Best is trial 0 with value: 0.17844455563947612.
[I 2025-09-02 10:35:58,731] Trial 10 finished with value: 0.16617724594527283 and parameters: {'n_estimators': 111, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'sqrt', 'class_weight_multiplier': 1256}. Best is trial 0 with value: 0.17844455563947612.
[I 2025-09-02 10:36:39,244] Trial 11 finished with value: 0.2257656439231514 and parameters: {'n_estimators': 300, 'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight_multiplier': 1635}. Best is trial 11 with value: 0.2257656439231514.
[I 2025-09-02 10:37:28,746] Trial 12 finished with value: 0.10743840829466719 and parameters: {'n_estimators': 298, 'max_depth': 16, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 0.5, 'class_weight_multiplier': 1211}. Best is trial 11 with value: 0.2257656439231514.
[I 2025-09-02 10:37:54,872] Trial 13 finished with value: 0.22851182691968566 and parameters: {'n_estimators': 191, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight_multiplier': 1997}. Best is trial 13 with value: 0.22851182691968566.
[I 2025-09-02 10:38:20,199] Trial 14 finished with value: 0.2268848275903374 and parameters: {'n_estimators': 182, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight_multiplier': 2072}. Best is trial 13 with value: 0.22851182691968566.
[I 2025-09-02 10:38:44,725] Trial 15 finished with value: 0.23310252982203017 and parameters: {'n_estimators': 181, 'max_depth': 10, 'min_samples_split': 20, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight_multiplier': 2161}. Best is trial 15 with value: 0.23310252982203017.
[I 2025-09-02 10:39:13,008] Trial 16 finished with value: 0.13191734072439995 and parameters: {'n_estimators': 179, 'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 3, 'max_features': 0.5, 'class_weight_multiplier': 3493}. Best is trial 15 with value: 0.23310252982203017.
[I 2025-09-02 10:39:38,696] Trial 17 finished with value: 0.026480836236933796 and parameters: {'n_estimators': 140, 'max_depth': 23, 'min_samples_split': 20, 'min_samples_leaf': 5, 'max_features': 0.5, 'class_weight_multiplier': 2024}. Best is trial 15 with value: 0.23310252982203017.
[I 2025-09-02 10:39:42,014] Trial 18 finished with value: 0.1878451603041767 and parameters: {'n_estimators': 211, 'max_depth': 14, 'min_samples_split': 17, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'class_weight_multiplier': 2278}. Best is trial 15 with value: 0.23310252982203017.
[I 2025-09-02 10:40:13,568] Trial 19 finished with value: 0.1049139582654351 and parameters: {'n_estimators': 189, 'max_depth': 18, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_features': 0.5, 'class_weight_multiplier': 747}. Best is trial 15 with value: 0.23310252982203017.
[I 2025-09-02 10:40:34,904] Trial 20 finished with value: 0.24710920577025258 and parameters: {'n_estimators': 155, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 7, 'max_features': 0.5, 'class_weight_multiplier': 1890}. Best is trial 20 with value: 0.24710920577025258.
[I 2025-09-02 10:40:56,179] Trial 21 finished with value: 0.24206870177177234 and parameters: {'n_estimators': 157, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 7, 'max_features': 0.5, 'class_weight_multiplier': 1864}. Best is trial 20 with value: 0.24710920577025258.
[I 2025-09-02 10:41:20,420] Trial 22 finished with value: 0.138772783414323 and parameters: {'n_estimators': 153, 'max_depth': 14, 'min_samples_split': 18, 'min_samples_leaf': 7, 'max_features': 0.5, 'class_weight_multiplier': 1505}. Best is trial 20 with value: 0.24710920577025258.
[I 2025-09-02 10:41:37,061] Trial 23 finished with value: 0.2292442893794072 and parameters: {'n_estimators': 122, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': 0.5, 'class_weight_multiplier': 2390}. Best is trial 20 with value: 0.24710920577025258.
[I 2025-09-02 10:42:01,390] Trial 24 finished with value: 0.15295352626325104 and parameters: {'n_estimators': 164, 'max_depth': 13, 'min_samples_split': 15, 'min_samples_leaf': 6, 'max_features': 0.5, 'class_weight_multiplier': 1924}. Best is trial 20 with value: 0.24710920577025258.
[I 2025-09-02 10:42:03,411] Trial 25 finished with value: 0.24927242772356628 and parameters: {'n_estimators': 133, 'max_depth': 11, 'min_samples_split': 19, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 1057}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:05,643] Trial 26 finished with value: 0.18067139676641913 and parameters: {'n_estimators': 131, 'max_depth': 15, 'min_samples_split': 17, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 921}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:07,455] Trial 27 finished with value: 0.1353883191294718 and parameters: {'n_estimators': 100, 'max_depth': 18, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 992}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:09,787] Trial 28 finished with value: 0.23011804758582116 and parameters: {'n_estimators': 145, 'max_depth': 12, 'min_samples_split': 18, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 1497}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:12,165] Trial 29 finished with value: 0.24307838501120824 and parameters: {'n_estimators': 166, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'class_weight_multiplier': 481}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:15,420] Trial 30 finished with value: 0.05665988828811787 and parameters: {'n_estimators': 167, 'max_depth': 26, 'min_samples_split': 16, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'class_weight_multiplier': 491}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:17,128] Trial 31 finished with value: 0.04470046082949308 and parameters: {'n_estimators': 125, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 41}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:19,340] Trial 32 finished with value: 0.21634267231158927 and parameters: {'n_estimators': 141, 'max_depth': 13, 'min_samples_split': 12, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 997}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:21,737] Trial 33 finished with value: 0.2424826835900661 and parameters: {'n_estimators': 167, 'max_depth': 11, 'min_samples_split': 19, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'class_weight_multiplier': 1396}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:24,746] Trial 34 finished with value: 0.1905007914090943 and parameters: {'n_estimators': 204, 'max_depth': 13, 'min_samples_split': 18, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'class_weight_multiplier': 455}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:27,141] Trial 35 finished with value: 0.23613221548111793 and parameters: {'n_estimators': 165, 'max_depth': 11, 'min_samples_split': 19, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 1369}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:29,681] Trial 36 finished with value: 0.23583820494207655 and parameters: {'n_estimators': 173, 'max_depth': 11, 'min_samples_split': 19, 'min_samples_leaf': 10, 'max_features': 'sqrt', 'class_weight_multiplier': 773}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:32,114] Trial 37 finished with value: 0.17960503183702228 and parameters: {'n_estimators': 149, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 1144}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:42:34,579] Trial 38 finished with value: 0.14227394060727394 and parameters: {'n_estimators': 133, 'max_depth': 21, 'min_samples_split': 16, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 1719}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:43:00,435] Trial 39 finished with value: 0.16829424938940138 and parameters: {'n_estimators': 117, 'max_depth': 12, 'min_samples_split': 19, 'min_samples_leaf': 10, 'max_features': 0.8, 'class_weight_multiplier': 619}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:43:03,938] Trial 40 finished with value: 0.21424142424981327 and parameters: {'n_estimators': 223, 'max_depth': 13, 'min_samples_split': 12, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'class_weight_multiplier': 1512}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:43:37,952] Trial 41 finished with value: 0.18510464381929953 and parameters: {'n_estimators': 160, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 8, 'max_features': 0.8, 'class_weight_multiplier': 2472}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:43:40,090] Trial 42 finished with value: 0.2425234903345502 and parameters: {'n_estimators': 153, 'max_depth': 11, 'min_samples_split': 16, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 1831}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:43:42,139] Trial 43 finished with value: 0.2397223488878756 and parameters: {'n_estimators': 134, 'max_depth': 12, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'class_weight_multiplier': 1364}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:43:44,803] Trial 44 finished with value: 0.1865732388557512 and parameters: {'n_estimators': 173, 'max_depth': 14, 'min_samples_split': 17, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 1772}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:43:46,378] Trial 45 finished with value: 0.23476800725071337 and parameters: {'n_estimators': 109, 'max_depth': 11, 'min_samples_split': 14, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 1163}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:43:49,468] Trial 46 finished with value: 0.17004803279240643 and parameters: {'n_estimators': 198, 'max_depth': 15, 'min_samples_split': 18, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'class_weight_multiplier': 1592}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:43:52,225] Trial 47 finished with value: 0.013157894736842105 and parameters: {'n_estimators': 146, 'max_depth': 30, 'min_samples_split': 16, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'class_weight_multiplier': 277}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:43:54,512] Trial 48 finished with value: 0.24748706171424456 and parameters: {'n_estimators': 153, 'max_depth': 12, 'min_samples_split': 19, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'class_weight_multiplier': 857}. Best is trial 25 with value: 0.24927242772356628.
[I 2025-09-02 10:44:37,620] Trial 49 finished with value: 0.06777139985958112 and parameters: {'n_estimators': 153, 'max_depth': 24, 'min_samples_split': 17, 'min_samples_leaf': 8, 'max_features': 0.8, 'class_weight_multiplier': 834}. Best is trial 25 with value: 0.24927242772356628.

      Best parameters found (Optuna): {'n_estimators': 133, 'max_depth': 11, 'min_samples_split': 19, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'class_weight_multiplier': 1057}
      Best F2 (class=1) score (CV): 0.2493

     Forecasting the test dataset...
     Forecasting done!
Best threshold for F2 score: 0.6162 with F2 score: 0.7368
     Calculation of the ROC curve...
     Calculation done
     Scoring...
     Scoring done

     Creating the metrics...